raiden-network/raiden-services

src/monitoring_service/database.py, src/monitoring_service/states.py, src/raiden_libs/test/mocks/client.py, tests/monitoring/fixtures/monitor_request.py, tests/monitoring/monitoring_service/test_handlers.py, tests/monitoring/monitoring_service/test_states.py, tests/monitoring/request_collector/test_store_monitor_request.py, tests/pathfinding/test_rest.py
With this change, all `MonitorRequest` objects contain valid signatures. I like how the API turned out and might split `HashedBalanceProof`s into signed and unsigned classes too, if there is general agreement that this is a nice way to handle signing.
=> Verify MR signatures on creation

src/pathfinding_service/cli.py
When starting to test we don't want to have all this noise hiding the message.
Related to #84
=> Suppress urllib3 connectionpool warnings

src/monitoring_service/blockchain.py, tests/monitoring/monitoring_service/test_blockchain.py
This commit fixes a bug that led to the UpdatedHeadBlockEvent only being
emitted every second block. The reason was a wrong comparison in the
blockchain filter logic.
=> Emit the UpdatedHeadBlockEvent on every block update

tests/monitoring/monitoring_service/test_cli.py
The logging test did not terminate for me because it got stuck in
`MonitoringService.start`. The actual MS implementation was meant to be
mocked in that test, too.
=> Mock MonitoringService in all MS cli tests

src/monitoring_service/database.py, src/monitoring_service/schema.sql
Storing it as JSON in the db is an unnecessary amount of flexibility and
might makes proper validation and future schema changes more
problematic.
=> Flatten update status in database

src/monitoring_service/handlers.py
We already use `non_closing_signer` to fetch the MR. If the MR is not by the non-closing participant, `None` is returned from the db and we correctly do nothing.
Closes #136
=> Remove obsolete comment, only matching MR is used

src/pathfinding_service/api/rest.py
As Ulo said:
> Hm ok apparently pkg_resources.get_distribution(pkg_name).version is the recommended way to do it and it seems to be much faster
=> Imrpove version number retrival and cache it

src/monitoring_service/service.py, src/raiden_libs/test/mocks/client.py, tests/monitoring/fixtures/server.py, tests/monitoring/monitoring_service/test_end_to_end.py
The matrix listener is still mocked out, but that can be tested well separately.
Closes #134.
=> Use the RC in the end-to-end test

src/raiden_libs/matrix.py
@Dominik1999 This is an issue I found late today and discussed a bit with Konrad. I hope that this fix does the trick, but the internet in the bus is so shitty that I cannot really test it.
Give it a try, hopefully it work. Otherwise @konradkonrad  is happy to help. 🍻 
The problem is that the client removed the message deserialization for all messages the services receive, so we have to do this ourselves now.
=> Fix message deserialisation after raiden client changes

src/raiden_libs/matrix.py, src/request_collector/cli.py, src/request_collector/server.py, tests/monitoring/request_collector/test_cli.py
Before, the RC exited immediately on startup. Now the process control is
given to `GMatrixClient.listen_forever`, which keeps the RC running until
the MatrixListener fails.
We could remove the `Greenlet` superclass from `RequestCollector` and
`MatrixListener`, as well as the `_run` and `stop` methods if we don't
plan to run them as greenlets at all. Currently we still do that in some
tests.
=> Keep RequestCollector running

src/monitoring_service/database.py
Otherwise the signature checks are broken. We should add tests with
different chain_ids!
=> Use correct chain_id when loading MRs

src/pathfinding_service/service.py
Just display stuff a bit nicer for debugging:
```
2019-03-12 16:11:33.954389 [info     ] Received message               [pathfinding_service.service] chain_id=4 channel_identifier=1 locked_amount=0 locksroot=0x0000000000000000000000000000000000000000000000000000000000000000 nonce=2 reveal_timeout=50 signature=0x6c996db8696bedae15e95577bc99a19072a95f5cb93aa4f7dd661f0f9f18fc484b3edbac6f770c45b9b36b00c3ef15542f95bde47fff16419d23463cbbc0d3161c token_network_address=0xbefc1ae9854719bb6598a751ee8daa8a04968a2e transferred_amount=5 type=UpdatePFS
```
=> Log received messages properly

src/monitoring_service/database.py, src/monitoring_service/handlers.py, src/monitoring_service/schema.sql, src/monitoring_service/service.py, tests/monitoring/monitoring_service/test_handlers.py
Merge after #159 .
Store scheduled events in DB as well
This commit moves scheduled events from memory to the database.
This makes them persistent, so that they are available after restarts
and makes sure that the DB is the single source of truth.
Fixes #157
=> Store scheduled events in DB as well

src/monitoring_service/database.py, src/monitoring_service/service.py, src/request_collector/server.py, tests/monitoring/monitoring_service/test_handlers.py
This is left over from the time where we accepted a `sync_start_block`
parameter on the command line. Now we either start from the saved sync
block or from 0 if none has been saved before.
Closes https://github.com/raiden-network/raiden-services/issues/168.
=> Remove `sync_start_block` from `load_state`

deployment/docker-compose.yml, requirements.txt, src/pathfinding_service/api/rest.py, src/pathfinding_service/cli.py, src/pathfinding_service/config.py, src/pathfinding_service/database.py, src/pathfinding_service/exceptions.py, src/pathfinding_service/model/__init__.py, src/pathfinding_service/model/iou.py, src/pathfinding_service/schema.sql, src/pathfinding_service/service.py, src/raiden_libs/marshmallow.py, tests/pathfinding/fixtures/network_service.py, tests/pathfinding/test_blockchain_integration.py, tests/pathfinding/test_payment.py, tests/pathfinding/test_rest.py
In addition to the main feature, two things in this PR need review/discussion:
I tried to consolidate the following tasks into a single dataclass:
* validating data passed via HTTP
* serializing data for HTTP responses
* serializing into basic types for db storage
* providing detailed types for typechecking
Have a look at the `IOU` and `IOURequest` classes and check if this is a good way to do this. We might also compare with raiden.
All subclasses of `APIException` will be automatically converted into proper HTTP error responses when raised. This allows raising errors in all functions instead of only allowing a return from the `Resource`. Right now I created a separate `exceptions.py` for the PFS, but if we keep this approach we probably want to move all or part of the exceptions into …
=> Add payment handling to PFS

.coveragerc, requirements.txt, setup.py, src/raiden_libs/test/fixtures/address.py, src/raiden_libs/test/fixtures/client.py, src/raiden_libs/test/fixtures/web3.py, tests/monitoring/fixtures/contracts.py, tests/monitoring/fixtures/server.py, tests/monitoring/monitoring_service/test_crash.py, tests/monitoring/monitoring_service/test_handlers.py, tests/monitoring/monitoring_service/test_states.py, tests/monitoring/request_collector/test_server.py, tests/pathfinding/fixtures/contracts.py, tests/pathfinding/test_blockchain_integration.py, tests/pathfinding/test_payment.py, tests/pathfinding/test_rest.py
The problems are solved by using the more recently maintained fixtures
from the raiden-contracts repo. Less code duplication, more brittle
cross repo dependencies.
Currently throws import errors due to circular import in raiden-contracts. Those are fixed in https://github.com/raiden-network/raiden-contracts/commit/ef561cbc2e396e239d97b97b40e610415d513f87 and should thus disappear once raiden gets a new contracts version. 
Closes https://github.com/raiden-network/raiden-services/issues/166.
=> Update to latest raiden-contracts release

tests/pathfinding/fixtures/network_service.py, tests/pathfinding/test_blockchain_integration.py
Tests should not connect to real matrix rooms. This is slow and makes
tests flaky.
=> Mock MatrixListener in tests

src/pathfinding_service/cli.py, tests/conftest.py
It was causing `socket.gaierror: [Errno -2] Name or service not known`
errors when run inside docker.
=> Disable gevent `thread` resolver for PFS

MANIFEST.in
They are required to run the services and since they are not python
files, they need to be included explicitly.
This should solve @rakanalh's error when running from the released version.
=> Include schema files in MANIFEST.in

src/monitoring_service/database.py, src/pathfinding_service/database.py
In accd17fd7b298057260848a604da321e28676855 a bug has been introduced
which causes failure on plain db names without specifying a path.
I thought `os.makedirs(os.path.dirname(filename), exist_ok=True)` would
work in all cases, but if not path segment is in `filename`, the
`dirname(filename) == ''` which is not a valid path for `makedirs`.
=> Fix db path creation for local dbs

Makefile, setup.cfg, src/pathfinding_service/api/rest.py, src/pathfinding_service/cli.py, src/raiden_libs/cli.py, src/request_collector/cli.py, src/request_collector/server.py
It's still allowed in tests. Tests don't need to be as strict as the
main code base.
Moving the mypy flags to `setup.cfg` makes IDE integration a bit easier.
=> Disallow untyped defs in whole `src`

src/pathfinding_service/service.py, src/pathfinding_service/utils/blockchain_listener.py, tests/pathfinding/test_blockchain_listener.py
One problem with `eth-tester` seems to be fixed.
Also we wrongly queried the end-block of the last filter call again in the next one.
Fixes #215
=> Fix BlockchainListener to not query blocks twice, improve tests

src/monitoring_service/database.py, src/monitoring_service/schema.sql, src/monitoring_service/service.py
When running the MS for the first time, this will skip all blocks before
Raiden contracts have been deployed.
=> Use `sync_start_block` in monitoring service

src/pathfinding_service/api.py, tests/pathfinding/test_rest.py
I decided against returning an empty list of routes to stay in line with
the existing error for the case when both nodes are present in the graph
but are not connected.
Closes https://github.com/raiden-network/raiden-services/issues/219.
=> Handle PFS requests where node is not in graph

requirements-dev.txt, src/pathfinding_service/blockchain.py, tests/pathfinding/test_blockchain_listener.py, tests/pathfinding/test_mocked_integration.py
In #217 I incorrectly changed the calculation of the `new_confirmed_head_number`.
This change made the number increase by 1 every call, which eventually resulted in asking for a not yet existing block. 
With the default settings this happened after roughly 8 * 10 seconds.
Fixes #223
=> Fix BlockchainListener crash

tests/pathfinding/test_rest.py
Using `hex` to generate the signature caused a lack of leading zeros in
some cases.
Closes https://github.com/raiden-network/raiden-services/issues/237.
=> Fix flaky IOU test

scenarios/simple_pfs_integration_without_reward.yml
This PR add a minimal viable happy path scenario for the PFS. 
Once this scenario passes, I think we have a some working version of the PFS.
Currently it doesn't work since the `assert_pfs_history` task doesn't work yet.
=> add initial pfs happy path scenario

src/pathfinding_service/__init__.py, src/pathfinding_service/api.py, src/pathfinding_service/cli.py, tests/pathfinding/fixtures/network_service.py, tests/pathfinding/test_blockchain_integration.py
The import in `__init__.py` was executed first when the PFS is executed
via `python -m pathfinding_service.cli` or the setuptools entry point.
This causes the gevent monkeypatching to be executed after SSL imports,
which in turn led to `RecursionError`s.
Closes https://github.com/raiden-network/raiden-services/issues/93.
=> Remove import from __init__.py (fix monkeypatch)

src/raiden_libs/cli.py
I don't see any reason for a confirmation when opening the keystore. I assume this happened only due to a confirmation being the default.
Closes #257.
=> Don't require password confirmation in cli

src/raiden_libs/gevent_error_handler.py, tests/pathfinding/conftest.py
The error handler allowed nesting of multiple handlers, which often went
wrong for me causing `RecursionError`s. This in turn obscured the real
error which made debugging tests unnecessarily hard.
Since we don't actually need to nest error handlers, I simplified the
handling code which solves the debugging problems for me.
=> Simplify gevent error handler

tests/pathfinding/test_rest.py
Requesting a path without IOU works for me. @palango @Dominik1999 can you reproduce a case where it fails due to lack of IOU when no service is set for the PFS?
=> Add test for requesting a path without IOU

src/pathfinding_service/api.py, src/raiden_libs/logging.py
For some reason Flask still logs on it's own, and structlog doesn't pick up that.
=> Add some logging to Flask requests

src/pathfinding_service/database.py, tests/pathfinding/test_service.py
We passed the values into sqlite as int, which caused SQLite to reject
then input values as too large if they were above 2^64. Fixed by passing
the values in as string.
=> Fix sqlite error on values larger than maxuint64

src/pathfinding_service/cli.py
As it is hidden, we don't need a help text anyways. 
Nice find ayways :)
=> Remove (wrong) help from --enable-debug

docs/index.rst, src/raiden_libs/cli.py, tests/monitoring/fixtures/server.py, tests/pathfinding/test_cli.py
This was ambiguous between token network registry and service registry.
=> Rename `--registry-address` CLI flag

src/raiden_libs/cli.py, tests/monitoring/monitoring_service/test_cli.py, tests/pathfinding/test_api.py, tests/pathfinding/test_cli.py
Structlog messes up capturing with `capsys` in some cases when not properly reset. That was hard to find.
=> Fix two reasons for flaky tests

tests/conftest.py, tests/pathfinding/test_api.py
Stop blindly killing all greenlets after the test. Instead cleanly
shut down the running greenlets. The `no_greenlets_left` fixture will
complain if you don't do it, so the tests stay clean in this regard.
Closes https://github.com/raiden-network/raiden-services/issues/308.
=> Clean up greenlet handling in tests

src/pathfinding_service/api.py, tests/pathfinding/test_api.py
Which allows running the Raiden client with a custom PFS without
manually passing the PFS' eth address to the client.
=> Include PFS' eth address in info endpoint

pylintrc, src/monitoring_service/handlers.py, src/monitoring_service/service.py, src/monitoring_service/states.py, src/pathfinding_service/api.py, src/pathfinding_service/cli.py, src/pathfinding_service/model/token_network.py, src/pathfinding_service/service.py, src/raiden_libs/cli.py, src/raiden_libs/gevent_error_handler.py, src/raiden_libs/matrix.py, src/raiden_libs/types.py, src/raiden_libs/utils.py, src/request_collector/server.py, tests/libs/fixtures/web3.py, tests/libs/test_matrix.py, tests/monitoring/fixtures/server.py, tests/monitoring/monitoring_service/test_cli.py, tests/monitoring/monitoring_service/test_end_to_end.py, tests/monitoring/monitoring_service/test_handlers.py, tests/monitoring/monitoring_service/test_states.py, tests/monitoring/request_collector/test_cli.py, tests/monitoring/request_collector/test_server.py, tests/pathfinding/fixtures/accounts.py, tests/pathfinding/fixtures/api.py, tests/pathfinding/fixtures/network_service.py, tests/pathfinding/test_blockchain_integration.py, tests/pathfinding/test_capacity_updates.py, tests/pathfinding/test_cli.py, tests/pathfinding/test_middleware.py
I've reduced the strictness of some checks and added a lot of `disable` comments, but now we can start eliminating those when touching the respective parts of the code and we won't accidentally add new code that violates one of these checks.
Relates to https://github.com/raiden-network/raiden-services/issues/280.
=> Enable more pylint checks

src/raiden_libs/gevent_error_handler.py
This was missed when fixing pylint.
Fixes #329
=> Use proper variable when checking exception

src/pathfinding_service/api.py, src/pathfinding_service/config.py, src/pathfinding_service/database.py, src/pathfinding_service/exceptions.py, src/pathfinding_service/model/__init__.py, src/pathfinding_service/model/feedback.py, src/pathfinding_service/model/token_network.py, src/pathfinding_service/schema.sql, tests/pathfinding/test_api.py, tests/pathfinding/test_database.py, tests/pathfinding/test_model.py
Part of #336 
This adds the feedback API to the PFS, I'd like to wait with merging this until I have the client changes done and tested.
Basically this PR adds a new ` /<token_network_address>/feedback` endpoint, which can be used to send feedback about routes to the PFS.
Some points for discussion:
- I don't store the sender of the feedback, as we can't be sure the person requesting a route is the actual source in the request. We'd need a signature in the request for that.
- I decided to return HTTP 200, even if the feedback was not accepted, the reasons for this are that the client's doesn't need to know and
- The time interval for feedback is currently set to 10mins
- Feedback is not yet persisted to the DB
=> Add feedback API

deployment/docker-compose.yml
The builder sometimes crashes and didn't have `restart: always` enabled.
=> Enable auto restart for builder

src/raiden_libs/matrix.py, src/request_collector/cli.py
Currently the RequestCollector doesn't start, as the RC greenlet is not started and thus the MatrixListener doesn't log in properly.
~This is not a nice solution yet, but I haven't found a nice way to wait until the startup process is finished properly. @ulope any hints? Probably some event that is set once the startup is finished would help?~
=> Start RequestCollector greenlet

deployment/docker-compose.yml
The SP nightly runner will use the pfs endpoints for the scenarios and for that we need debug enabled.
=> enable debug on the pfs services

requirements.txt, setup.py, src/monitoring_service/states.py, src/pathfinding_service/api.py, src/pathfinding_service/database.py, src/pathfinding_service/service.py, src/raiden_libs/database.py, src/raiden_libs/marshmallow.py, src/raiden_libs/matrix.py, tests/libs/test_matrix.py, tests/monitoring/request_collector/test_server.py, tests/pathfinding/fixtures/iou.py, tests/pathfinding/fixtures/network_service.py, tests/pathfinding/test_api.py, tests/pathfinding/test_capacity_updates.py, tests/pathfinding/test_middleware.py
* raiden switched it's message implementation to dataclasses
* update from marshmallow 2 to 3, which has API changes
This still needs https://github.com/raiden-network/raiden/pull/4127 before passing CI.
=> Update raiden and marshmallow

.travis.yml, requirements-dev.txt, src/pathfinding_service/cli.py, src/request_collector/cli.py, tests/conftest.py, tests/pathfinding/fixtures/api.py
The blocker for this was that gevent monkeypatching broke xdist. By
skipping `subprocess` and `thread` monkeypatching, this can be avoided.
We also need to make sure that not all processes choose the same port.
At least in my tests, choosing a free port by binding to port 0 did not
cause problematic race conditions, although I'm not sure that it always
works.
=> Allow running tests in parallel with pytest-xdist

src/pathfinding_service/api.py, tests/pathfinding/test_api.py
Stringy values turned out to be harder to maintain and harder to test.
Part of #336
=> Make success field of feedback boolean

.coveragerc, tests/pathfinding/test_middleware.py
As required according to
https://coverage.readthedocs.io/en/coverage-4.2/config.html#run
Hopefully, this will fix our flaky coverage.
=> Set concurrency setting for coverage calculation

src/pathfinding_service/api.py, src/pathfinding_service/model/token_network.py, src/pathfinding_service/service.py, tests/pathfinding/fixtures/__init__.py, tests/pathfinding/fixtures/api.py, tests/pathfinding/fixtures/network_service.py, tests/pathfinding/test_fee_schedule.py, tests/pathfinding/test_graphs.py, tests/pathfinding/test_service.py
Keeping a per token network mapping of addresses to presences results in
more complicated code, bugs (#380) and inefficiencies (#350).
This commit changes the presence tracking to be handles in the service
itself.
Fixes #380
Fixes #350
=> Use a global presence mapping

src/monitoring_service/handlers.py, src/monitoring_service/service.py, tests/monitoring/monitoring_service/test_handlers.py
We have a global contract manager now, so that one is not needed,
anymore.
=> Remove contract manager from `Context`

requirements.txt, src/pathfinding_service/database.py, src/pathfinding_service/exceptions.py, src/pathfinding_service/model/channel_view.py, src/pathfinding_service/model/token_network.py, src/pathfinding_service/schema.sql, src/pathfinding_service/service.py, src/raiden_libs/matrix.py, tests/pathfinding/test_fee_schedule.py, tests/pathfinding/test_service.py
The messages have to be stored until a ChannelOpened event has been
received, if that is no the case yet when receive the `FeeUpdate`. Still missing:
- Nonce handling
- Scenario to test the client/PFS integration
=>  Receive and handle `FeeUpdate` generated by client

src/monitoring_service/cli.py, src/monitoring_service/service.py, src/pathfinding_service/cli.py
This caused some mismatches which eventually led to failing scenarios.
=> Use clients default for confirmation blocks setting

Dockerfile, deployment/docker-compose.yml, deployment/services.env
Before the services ran as root in the docker file. After the change to
a user, it cannot read the keyfile any more. Therefore the keyfile is
now put under `/data`.
=> Fix depoloyment

src/raiden_libs/database.py
Example output:
```
2019-07-02 12:47:41.831588 [info     ] Starting Raiden Pathfinding Service [__main__]
2019-07-02 12:47:41.863405 [info     ] PFS payment address            [pathfinding_service.service] address=0x062C12c01D0f17fC9eAa33940D994594d91a0182
2019-07-02 12:47:41.863770 [info     ] Opening database               [raiden_libs.database] filename=state/pfs-rinkeby.db
2019-07-02 12:47:41.865866 [error    ] Mismatch between current settings and settings saved in db: DB was created with token_network_registry_address='0xd353c140CB3B2B994672784B7363928B8191B884', current_value is '0xCBee035Df4E3f2b40506c4cCc7be4D76407F7FF7'! Either fix your settings or start with a fresh db. WARNING: If you delete your db, you will lose earned fees! [raiden_libs.database]
Exiting...
2019-07-02 …
```
=> Provide nice error when settings in db don't match

requirements.txt, src/monitoring_service/cli.py, src/pathfinding_service/cli.py, src/raiden_libs/cli.py, src/request_collector/cli.py
This is done by setting the sentry dsn to the env varaible `SENTRY_DSN`
I didn't make this a CLI option because this way we can initialize sentry earlier, but it might me bore intuitive as an CLI arg.
Fixes #406
=> Add option to send reports to sentry

src/raiden_libs/matrix.py, tests/libs/test_matrix.py
This uses far more mocking than I like, but I didn't see a simple way to
test this without having it do network stuff apart from using mocks.
Fixes https://github.com/raiden-network/raiden-services/issues/458.
=> Fix 'MatrixListener' has no attr. 'rate_limiter'

.circleci/config.yml, .travis.yml
In the raiden client we already use CircleCI and are happier with it than with Travis. The change seems simple enough and even with this basic configuration, we are faster than Travis (~2:45 vs ~3:45).
I'll keep both Travis and CircleCI on for a while to see if things run as intended. We can remove Travis when we're confident enough. I just disabled the codecov upload by Travis to avoid duplicate uploads.
=> Configure CircleCI

.circleci/config.yml
* Store pip cache
* Don't create venv if already present
* Turn off pip progress bar (spams log file)
I've already observed a CI run in just 1:23 using this settings:
https://circleci.com/gh/raiden-network/raiden-services/3#artifacts/containers/0
=> CircleCI configuration fine tuning

deployment/builder/app/main.py, deployment/docker-compose.latest.yml, deployment/docker-compose.local.yml, deployment/docker-compose.yml
The docker-compose files provided now use the hub.docker.com
registry to pull built images.
This replaces the builder's build functionality with an
update functionality - images are no longer built
directly from the repo - instead, we let hub.docker.com
handle the build process. Images are updated using
`docker-compose pull && docker-compose restart` to
download the newest images for the configured tag.
Additionally, a docker-compose.latest.yml has been added
as a drop-in replacement for docker-compose.override.yml,
which is a more explicit name for the file imo.
Doc strings have been added to the compose yamls.
Exception handling was slightly refacored in the builder app.
=> [FEAT-#80] Update docker setup to use docker registry

requirements.txt, src/raiden_libs/logging.py
This add sentry-structlog to the strctlog processors, so that all logs
with level WARNING or higher get automatically reported to sentry.
=> Add sentry-structlog processor

requirements.txt, src/raiden_libs/cli.py, src/raiden_libs/gevent_error_handler.py, src/raiden_libs/logging.py
We will still get garbled log messages like
```
[0m] [1mError log right before exception[0m [[34m[1mraiden_libs.matrix[0m] [36mvalue[0m=[35m2[0m
```
but at least the traceback will be clean and the error grouping works.
=> Bring Sentry configuration into a usable state

adr/003-mediation-fees.md
* The proportional fee has been changed from float to int to facilitate
message signing
* before/after were the wrong order in the ADR
=> Minor corrections for mediation fee ADR

src/pathfinding_service/database.py, src/pathfinding_service/model/channel_view.py, src/pathfinding_service/model/token_network.py, src/pathfinding_service/schema.sql, src/pathfinding_service/service.py, src/raiden_libs/blockchain.py, src/raiden_libs/events.py, tests/pathfinding/fixtures/network_service.py, tests/pathfinding/test_blockchain_integration.py, tests/pathfinding/test_capacity_updates.py, tests/pathfinding/test_graphs.py, tests/pathfinding/test_service.py
Handling the event turned out to be a source of issues. Besides, it
doesn't provide any advantages over just using the capacity updates from
the nodes.
This commit removes all internal handling of the deposit event.
Fixes https://github.com/raiden-network/raiden-services/issues/494
=> Remove handling of ChannelNewDeposit event

requirements-dev.txt, setup.cfg, src/monitoring_service/handlers.py, src/raiden_libs/cli.py
~~Merge after #496~~
Updates the dev dependencies and enables a new mypy check
=> Update dev deps and add new mypy check

Makefile
Otherwise `make dist` won't do anything when there is a `dist` directory.
=> Don't treat `dist` dir as result of `dist` target

src/pathfinding_service/service.py, tests/pathfinding/test_payment.py, tests/pathfinding/test_service.py
Otherwise `changed_cvs` will not be initialized.
Closes #500
=> Return early in case of unknown message type

src/monitoring_service/service.py, tests/monitoring/monitoring_service/test_service.py
This waits for confirmation blocks before checking the  status of pending transactions.
Follow-up for #502
=> Confirmed receipts

src/monitoring_service/database.py, src/monitoring_service/handlers.py, src/monitoring_service/schema.sql, src/monitoring_service/states.py, tests/monitoring/monitoring_service/factories.py, tests/monitoring/monitoring_service/test_end_to_end.py, tests/monitoring/monitoring_service/test_handlers.py
The old name is misleading!
This change breaks the db compatibility.
=> Rename `closing_tx_hash` to `monitor_tx_hash`

src/pathfinding_service/api.py, src/pathfinding_service/model/token_network.py, src/raiden_libs/utils.py, tests/pathfinding/fixtures/network_service.py, tests/pathfinding/test_graphs.py
It showed in #520 that in bigger token networks the search was blocking
the PFS for longer intervals. The main reason for that was that the path
finding was trying many routes where participants were offline.
This can easily be improved by pruning the graph on unreachable nodes
before the routing, so that the graph on which the search is done
consists only of reachable nodes.
This can be improved further in the future by also pruning channels with
to little capacity, etc.
Fixes #520
=> Graph pruning

requirements.txt, src/monitoring_service/states.py, src/raiden_libs/matrix.py, tests/monitoring/fixtures/server.py, tests/pathfinding/fixtures/network_service.py, tests/pathfinding/test_claim_fees.py
Update client and contracts deps
-  `start` should be called just before login is performed on the client. Stop somewhere before the client it disconnected
⚠️ Don't merge before the hackathon, as we don't want to deploy this yet.
=> Update to latest Raiden and contracts

src/raiden_libs/matrix.py
Incoming messages are already logged by the services, so we don't need
to do that at the matrix client level.
=> Remove unnecessary log in matrix

src/monitoring_service/handlers.py, src/pathfinding_service/api.py, src/raiden_libs/constants.py, tests/monitoring/monitoring_service/test_handlers.py, tests/pathfinding/test_payment.py
2 was too high for pfs and we have pessimistic assertion function
2 seems good for the pfs risk margin
fixes https://github.com/raiden-network/raiden/issues/4825
=> Split udc_margin_default for MS and PFS,

src/pathfinding_service/api.py, tests/pathfinding/test_api.py
as requested in
https://github.com/raiden-network/raiden-services/issues/547#issuecomment-536211768
Tested in Chromium locally (using --explicit-ports-allowed).
Closes https://github.com/raiden-network/raiden-services/issues/547
=> Set more CORS headers

requirements.txt, src/pathfinding_service/model/channel.py, tests/pathfinding/test_fee_schedule.py
Use `fee_receiver` and `fee_sender` from raiden to get the latest fee calculation. Those are currently in a test utils package and should be moved in a following PR.
Closes https://github.com/raiden-network/raiden-services/issues/563.
=> Iteration in fee approximation

setup.py
=> Add long description to package information

CHANGELOG.md, deployment/docker-compose.latest.yml, deployment/docker-compose.yml, deployment/update.sh
With these settings, we should be able to run our last release on
services-test while the latest commit runs on services-dev. The builder
will need changes in another PR to work as intended.
=> Configure docker to have services-dev and -test

deployment/builder/app/main.py, deployment/docker-compose.latest.yml, deployment/docker-compose.yml, deployment/update.sh
The builder will now only care about the services, not about updating
itself, the docker-compose-files or traefik. These changes are rare and
can be done manually.
The builder (or the `update.sh` to be more precise) is also now able to
understand the difference between the `dev` and `test` deployments.
Closes https://github.com/raiden-network/raiden-services/issues/80.
=> Simplify builder

deployment/docker-compose.latest.yml, deployment/docker-compose.yml
=> Don't restart registration tasks

src/pathfinding_service/constants.py, src/pathfinding_service/service.py
Until now we only started matrix but didn't wait for completions of the
initialization.
This could lead to problems when a blockchain event was processed before
the sync token was set.
=> Wait for matrix to completetely start

requirements.txt, src/pathfinding_service/model/token_network.py
After doing this, it's easier to integrate the new `raiden-contracts`. `raiden-contracts` first gets integrated to raiden:develop.
=> Upgrade raiden version to the current develop

requirements.txt
This switches the ServiceRegistries to the correct instances that can be deprecated.
Also a bug-fix enables deployments on private networks.
=> Upgrading raiden-contracts to 0.33.3

src/pathfinding_service/service.py
When the matrix server did not respond and the `login` was hanging, the
timeout just passed and the code continued running. This led to
misleading error messages. Better fail early!
=> Fail if matrix does not start up in time

requirements.txt, src/pathfinding_service/api.py, src/pathfinding_service/model/channel.py, src/pathfinding_service/model/token_network.py, src/raiden_libs/matrix.py, tests/pathfinding/test_api.py, tests/pathfinding/test_database.py, tests/pathfinding/test_fee_schedule.py, tests/pathfinding/test_service.py
Fixes #619 
Relies on https://github.com/raiden-network/raiden/pull/5250
This makes the PFS expect non-timezones datetimes everywhere and adds validation for this.
This also updates raiden, updates marshmallow[-dataclass] and adapts some matrix code.
=> Update raiden and related deps

deployment/.env.template, deployment/docker-compose.latest.yml, deployment/docker-compose.yml
I deviated from the planned tag scheme to keep the configuration simple and the naming consistent. Now the container name will be used as part of the tag, resulting in tags like `raiden.dev_pfs-rinkeby-with-fee_1`.
Results are visible on [Kibana](http://logs.raiden.network/app/kibana#/discover/18d7f580-06f2-11ea-98a2-67045732bdf3?_g=(filters%3A!()%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-5m%2Cto%3Anow))).
Closes https://github.com/raiden-network/raiden-services/issues/602
=> Log to fluentd

src/raiden_libs/cli.py, tests/conftest.py
This will create stack profiling data for use with https://github.com/brendangregg/FlameGraph.
Will only work reliably after https://github.com/raiden-network/raiden-services/pull/652 is merged.
Closes https://github.com/raiden-network/raiden-services/issues/643
=> Add profiling options to services and tests

src/pathfinding_service/exceptions.py, src/pathfinding_service/model/channel.py, src/pathfinding_service/model/token_network.py, src/pathfinding_service/service.py, tests/libs/test_matrix.py, tests/pathfinding/test_fee_updates.py, tests/pathfinding/test_service.py
Until now capacity updates were properly testsed, but not fee updates.
This improves this a bit.
=> Improve FeeUpdate tests

src/raiden_libs/matrix.py, tests/libs/test_matrix.py
Fixes #634, https://github.com/raiden-network/raiden-services/issues/630
This reverts https://github.com/raiden-network/raiden-services/pull/609 as we now have one alias for the same broadcast room on all servers.
=> Revert join all rooms

src/pathfinding_service/model/token_network.py
This reworks the path validity checking a bit. Now it checks first if
the path has enough capacity for the payment without fees before
calculating fees.
This should improve speed and also give clearer errors when payments
fail because of missing capacity.
=> Rework path validity checking

pylintrc, src/pathfinding_service/api.py, src/pathfinding_service/model/token_network.py, tests/pathfinding/test_token_network.py
This should make it easier to known what's going on when we get "no
route found" errors.
=> Provide specific error message for common errors

src/pathfinding_service/api.py, tests/pathfinding/test_api.py
Fixes https://github.com/raiden-network/raiden/issues/5421 
This was one idea why https://github.com/raiden-network/raiden/issues/5421 might happen.
The test was close, but didn't catch all cases.
The second commit fixes the problem and adds a regression test.
=> Add test that empty route requests are returned in debug endpoint

src/pathfinding_service/api.py, tests/pathfinding/test_api.py
Fixes #688 
I also think we should rename `registry_address` to `token_network_registry_address`. Opinions on that?
@andrevmatos @kelsos @nephix This changes the info endpoint of the API.
=> Add UDC info to /info endpoint

src/pathfinding_service/database.py, tests/pathfinding/test_database.py
Merge after #694 
This fixes a problem in `DB.delete_channel` and adds add test for it.
=> Fix channel delete

src/pathfinding_service/database.py, src/pathfinding_service/model/token_network.py, src/pathfinding_service/service.py, tests/pathfinding/test_database.py, tests/pathfinding/test_service.py
Remove loading a channel just to delete it then. 
Instead, `delete_channel` expects to delete 0 or 1 row now.
=> Optimize channel deletion

src/pathfinding_service/api.py, src/pathfinding_service/database.py, src/pathfinding_service/model/token_network.py, src/pathfinding_service/schema.sql, tests/pathfinding/test_api.py, tests/pathfinding/test_database.py, tests/pathfinding/test_fee_schedule.py, tests/pathfinding/test_graphs.py
Fixes https://github.com/raiden-network/raiden/issues/5503
If the PFS is restarted while a scenario is running the data of the PFS
requests will be lost, which has led to scenario failures. This commit
changes the debug endpoint to use data persisted in the database, so
that restarts will no lead to a problem.
Note: This is relying on the feedback data, which does not contain all
the requests. Specifically, requests which failed with a validation
error are not included in the table, therefore are still successtible to
loss of data.
=> Using persistent data for Path debug endpoint

src/pathfinding_service/api.py, tests/pathfinding/test_api.py
This information is useful to fix race conditions among the Raiden
client and the PFS server. It allows the Raiden node to wait for the PFS
to synchronize with the same state it expects.
=> Added confirmed block number to info api

src/pathfinding_service/api.py, src/pathfinding_service/model/token_network.py, src/pathfinding_service/service.py, src/pathfinding_service/typing.py, src/raiden_libs/matrix.py, tests/libs/test_matrix.py, tests/pathfinding/fixtures/__init__.py, tests/pathfinding/fixtures/api.py, tests/pathfinding/fixtures/network_service.py, tests/pathfinding/test_fee_schedule.py, tests/pathfinding/test_graphs.py, tests/pathfinding/test_service.py, tests/pathfinding/test_token_network.py, tests/pathfinding/utils.py
Instead of having a copy of the availability in the PFS, this changes
the code to rely on the data available in the UserAddressManager, which
already tracks the data. This is done just to simplify the code
(hopefully), and to remove the changes of data desynchronization.
=> Removing extra mapping for address availability.

src/pathfinding_service/api.py, src/pathfinding_service/database.py, tests/pathfinding/test_api.py
We changed the way multiple requests were returned, this commit restores
the old behaviour.
=> Revert PFS requests debug endpoint to prior behaviuor

requirements-dev.txt, requirements.txt, src/monitoring_service/states.py, src/pathfinding_service/database.py, tests/pathfinding/test_api.py
Required changes:
- avoid using pack_data
- `dump` yields strings for some numbers. Cast them back to int before
calling `hex256`.
=> Update to latest raiden and raiden-contracts

src/raiden_libs/cli.py
This make it easy to spot if an error happened on `dev` or `test`
services.
=> Configure sentry environment

requirements.txt, src/raiden_libs/matrix.py
Because we use one ethereum account for both PFS and MS, we need to
whitelist the correct broadcast room in each service, so that we don't
receive the other messages.
This is a pure performance optimization.
Fixes #713
=> Use matrix sync filter to only listen on selected broadcasting room

src/pathfinding_service/cli.py, src/pathfinding_service/service.py, src/raiden_libs/matrix.py, tests/libs/test_matrix.py
We were waiting on `event`s that never came when the greenlet we're
waiting for threw an exception at an unfortunate time. Because we we're
stuck in the `wait`, we did not event collect and raise the exception
from the underlying greenlet.
If should probably have split some of the changes in `matrix.py` into a
separate commit, but I don't think it's worth the effort to pull the
changes apart, now.
=> Use `AsyncResult` to raise errors while waiting

src/request_collector/server.py
Before we had `listen_forever` and `start` to run the MatrixListener in
a blocking respectively non-blocking way. Now we can use the same code
path to handle both cases.
Unfortunately, `Greenlet.run` is not documented in the gevent
documentation. But it seems to do exactly what we want here. If we want
to use something documented instead, we could do
```
matrix_listener.start()
matrix_listener.get()
```
instead.
Fixes https://sentry.io/share/issue/bfa38740026e44f1a1deaf8d92415719/
=> Use `MatrixListener.run` in request collector

src/monitoring_service/handlers.py, src/monitoring_service/service.py, tests/monitoring/monitoring_service/test_end_to_end.py, tests/monitoring/monitoring_service/test_service.py
Fixes https://github.com/raiden-network/raiden-services/issues/721
We used to trigger scheduled events based on the confirmed block, which lets valuable time pass. Especially in the scenarios with short settle timeouts the confirmation timeout of 5 blocks led to some flakyness.
This is possible because triggered events only rely on block number, and not on certain events that might change during a chain reorg.
=> Trigger scheduled events earlier

requirements.txt, src/monitoring_service/cli.py, src/monitoring_service/database.py, src/monitoring_service/states.py, src/pathfinding_service/cli.py, src/pathfinding_service/database.py, src/pathfinding_service/model/channel.py, src/pathfinding_service/model/token_network.py, src/raiden_libs/blockchain.py, src/raiden_libs/database.py, src/raiden_libs/logging.py, src/raiden_libs/marshmallow.py, src/raiden_libs/matrix.py, src/raiden_libs/register_service.py, tests/monitoring/fixtures/factories.py, tests/monitoring/monitoring_service/test_crash.py, tests/monitoring/monitoring_service/test_database.py, tests/monitoring/monitoring_service/test_end_to_end.py, tests/monitoring/monitoring_service/test_handlers.py, tests/monitoring/request_collector/test_server.py, tests/pathfinding/fixtures/iou.py, tests/pathfinding/test_database.py, tests/pathfinding/test_graphs.py, tests/pathfinding/test_service.py
With PR [#5734](https://github.com/raiden-network/raiden/pull/5734) the synced event how it is used here is renamed to `processed`. Thats what is desired here in the PFS which is the current sync to be processed.
=> change event name to processed due to PR #5734 in raiden

src/monitoring_service/handlers.py, tests/monitoring/monitoring_service/test_end_to_end.py
Unfortunately, parity does the gas estimation on the current block instead of the next one, so we have to wait for the first allowed block to be finished to send the transaction successfully on parity.
At least this is what I see from my experimentation. I don't have any parity docs or code snippets to prove it.
=> Call `monitor` when first allowed block is mined

src/monitoring_service/service.py
That is already used at the name for the first parameter. So if you
write
```python
log.error('Error', event=ev)
```
that is equivalent to
```python
log.error(event='Error', event=ev)
```
which must fail.
Resolves
https://sentry.io/organizations/raiden-network/issues/1262420995/?project=1509055.
=> Structlog can't take `event` as kwarg

src/monitoring_service/handlers.py, src/monitoring_service/service.py, tests/monitoring/monitoring_service/test_end_to_end.py, tests/monitoring/monitoring_service/test_handlers.py
Fixes #734 
This fixes the claim of the MS reward by pushing the transaction back one block. This is necessary because of the same parity problem we already discovered in https://github.com/raiden-network/raiden-services/pull/728
As we have no time pressure to claim early, adding one block doesn't hurt.
I locally tested this with MS1 and it fixed the run.
=> Fix reward claim

deployment/docker-compose.latest.yml
This was missing, so the container started on the `stable` instead of
the `latest` image.
=> Add override for `registration-goerli-backup`

deployment/docker-compose.yml, src/raiden_libs/service_registry.py
Now that we have subcommands, we also need to adjust the name of the envvars, so that click finds them.
Resolves #751
=> Fix envvar names for deployment

src/pathfinding_service/api.py, tests/pathfinding/test_payment.py
=> More error_details on DepositTooLow

src/monitoring_service/cli.py, src/monitoring_service/service.py, src/pathfinding_service/cli.py, src/pathfinding_service/constants.py, src/pathfinding_service/service.py, src/raiden_libs/constants.py, tests/monitoring/fixtures/server.py, tests/monitoring/monitoring_service/test_crash.py, tests/pathfinding/fixtures/network_service.py, tests/pathfinding/test_blockchain_integration.py, tests/pathfinding/test_service.py
The defaults made it hard to understand which setting was used where,
now stuff is a bit longer but more explicit.
=> Remove default values for prameters in services

src/pathfinding_service/database.py, src/pathfinding_service/service.py
In https://github.com/raiden-network/raiden/issues/5443, we had a problem with two PFSs sharing the same DB, which
lead to each of the PFSs processing roughly half of the blocks. Since
that was time consuming to debug, we should prevent that situation from
happening, again.
Our first approach was to prevent any access to the db by other
processes by acquiring an exclusive lock during the whole PFS runtime.
But this also prevents us from claiming PFS fees while the PFS is
running, since we need to mark the claimed IOUs in the db.
Using a single transaction when processing a block does not solve this
problems, since each PFS could still read the block number, process the
block and save the block number without any conflict. The processing of
blocks would only be serialized between the two …
=> Check block numbers instead of locking exclusively

src/monitoring_service/cli.py, src/monitoring_service/constants.py
We don't have a communication channel to establish a good reward during
runtime, so using the same fixed value is best in the meantime.
This also prevents MS operators from accidentally not demanding a
reward, which is a bad idea since they have to pay transaction fees.
=> Change MS DEFAULT_MIN_REWARD to Raiden's default

src/pathfinding_service/api.py, src/pathfinding_service/cli.py, tests/pathfinding/fixtures/api.py
As @kelsos noticed, we don't provide a way to choose the port used by
the PFS. This is an unusual and unnecessary limitation for a service.
=> Add cli option to set PFS port

src/pathfinding_service/api.py, src/raiden_libs/matrix.py, tests/pathfinding/fixtures/network_service.py, tests/pathfinding/test_api.py
This allows checking whether the PFS and client are connected to the
same matrix federation.
=> Add matrix server to info endpoint

requirements-dev.txt, src/raiden_libs/cli.py
This adds the `--gas-price` CLI option from raiden to the services. 
It doesn't make much sense for the PFS, so one could argue to move it out of  `blockchain_options` or make it optional.
=> Add gas price CLI option

src/raiden_libs/matrix.py
In that case just skip the message.
Related to https://github.com/raiden-network/raiden/issues/6128
=> Catch TransportError if displayname can not be read

src/monitoring_service/constants.py, src/monitoring_service/service.py, src/pathfinding_service/service.py, src/raiden_libs/blockchain.py, src/raiden_libs/states.py, tests/libs/fixtures/web3.py, tests/monitoring/monitoring_service/test_crash.py, tests/pathfinding/test_service.py
This PR adds adaptive blockchain syncing to the services similar to what https://github.com/raiden-network/raiden/pull/6092 did in Raiden.
Mid-term we should try to merge the two systems as there is a lot of duplicated effort.
This is the minimal impact PR I could build, I have some refactorings at hand but are hesitant to merge them so close to release.
This measures the time the `eth_getLogs` RPC call takes and adjusts the query range accordingly. In comparison to https://github.com/raiden-network/raiden/pull/6092 I chose to reduce the range more aggressively when a timeout is hit.
Resolves https://github.com/raiden-network/raiden-services/issues/782
=> Adaptive blockchain syncing

src/pathfinding_service/claim_fees.py, src/pathfinding_service/database.py, tests/pathfinding/test_claim_fees.py
Fixes #789 
Add an option to load only IOUs that are still valid and use that for the claim script.
=> Check if IOUs expiration is still valid

src/raiden_libs/service_registry.py
Withdraws are allowed immediately if the ServiceRegistry has been
deprecated.
=> Check for deprecation of SR before withdraw

src/monitoring_service/handlers.py, src/monitoring_service/service.py, src/pathfinding_service/service.py, src/raiden_libs/blockchain.py, src/raiden_libs/database.py, src/raiden_libs/events.py, src/raiden_libs/states.py, tests/libs/fixtures/web3.py, tests/libs/test_blockchain.py, tests/monitoring/monitoring_service/factories.py, tests/monitoring/monitoring_service/test_crash.py, tests/monitoring/monitoring_service/test_end_to_end.py, tests/monitoring/monitoring_service/test_handlers.py, tests/pathfinding/test_service.py
Follow-up to #783 
During the work on adaptive syncing I saw some opportunities to refactor stuff to reduce duplicated code, but didn't want to merge it back then.
This is mostly about removing the token network addresses from the blockchain state class. This make the code paths of MS and PFS similar and will allow to factor out the code there.
We now need to query the token network from the DB every time a new block is queried, but this only happens once per new block, so that shouldn't hurt.
=> WIP: Further refactor

src/raiden_libs/blockchain.py, tests/libs/test_blockchain.py, tests/monitoring/monitoring_service/test_end_to_end.py
On deployments with multiple token networks this lowers the number of
RPC requests by a big margin.
As we are interested in all events we do not need the filter topics. With them gone we can query multiple contracts at the same time. For now I chose to only do this for the token networks, as it is the easiest to do.
Part of https://github.com/raiden-network/raiden-services/issues/672
=> Batch the RPC request for token network events

src/pathfinding_service/api.py, tests/pathfinding/utils.py
This accesses an internal member of the user address manager. I consider
this acceptable because it is only used in a debugging endpoint. If this
number is useful in the long run, then we can add a proper way to get
the information from the user address manager.
See https://github.com/raiden-network/raiddit/issues/43.
=> Show number of online nodes in debug stats

requirements.txt, src/pathfinding_service/service.py
`raiden` and `raiden-contracts` need to be explicitely installed from their respective git branch `raiddit`.
=> [Raiddit] Fix raiddit requirements

src/pathfinding_service/model/token_network.py, tests/pathfinding/test_graphs.py
We only ask the PFS for routes in direct channels to gather global
information for the raiddit demo. In production use, these requests
would not get sent at all. To avoid slowing doing the PFS during the
demo too much, add a simple shortcut for that case.
=> Don't do complicated routing for direct channels

src/pathfinding_service/api.py, src/pathfinding_service/constants.py, src/pathfinding_service/model/token_network.py, tests/pathfinding/test_api.py, tests/pathfinding/test_graphs.py, tests/pathfinding/utils.py
When a Raiden node joins a token network, it should connect to nodes
which will be able to mediate payments. The PFS has a global view and
should have an easier time to find such nodes than the client.
See https://github.com/raiden-network/raiden-services/issues/684
The suggested partners are cached for one hour, which makes it
reasonable to offer this service without requiring fees. The amount of
results is fixed to make caching simpler.
The results are ordered and choosing just the first entry will be
sufficient for most use cases. For less common cases and for debugging,
additional scoring information is provided (The overall score as
`score`, as well as `centrality`, `uptime` and `capacity`). There is no
long term guarantee regarding the meaning of the specific values, but
greater …
=> Add `suggest_partner` api endpoint

Makefile, pyproject.toml, src/pathfinding_service/api.py, src/raiden_libs/blockchain.py, src/raiden_libs/matrix.py, tests/libs/test_blockchain.py, tests/libs/test_service_registry.py, tests/monitoring/monitoring_service/test_end_to_end.py, tests/pathfinding/fixtures/network_service.py, tests/pathfinding/test_api.py, tests/pathfinding/test_graphs.py
This is necessary for
- raiden-network/raiden-service-bundle#187
- raiden-network/raiden#6442
With those PRs the set of federation servers can become disjunct between different Raiden client versions.
Therefore we can't rely on the previous check in the Raiden client if the PFS' server is in the known servers set.
The RoomID is uniquely identifying a specific broadcasting room and can therefore be used as a better information source for this check.
=> Return PFS broadcast room id in info response

CHANGELOG.md, src/monitoring_service/api.py, src/pathfinding_service/api.py, tests/monitoring/monitoring_service/test_api.py, tests/pathfinding/test_api.py
These can't be deserialized correctly by all browsers, otherwise.
=> Use str to represent uint256 in JSON info endpoint

CHANGELOG.md, src/raiden_libs/service_registry.py, tests/libs/test_service_registry.py
This fix waits for `transaction_receipt["blockNumber"] + Confirmation interval` before sending a new transaction.
Also it waits on the transaction receipt to have a key "blockNumber". Parity returns a receipt of a non mined transaction with missing "blockNumber" field. 
The fix is done in the service registry script. Should also be checked in other code parts.
fixes: #855
=> fix transaction failing because prev one isnt in current chain state

src/monitoring_service/api.py, src/pathfinding_service/api.py, tests/monitoring/fixtures/api.py, tests/monitoring/monitoring_service/test_api.py
The metrics endpoint shouldn't be nested below `/api`.
=> Fix metrics endpoint path

src/pathfinding_service/cli.py, src/pathfinding_service/constants.py, src/raiden_libs/constants.py
This has been a problem when starting services that have not been
running in a while or were started for the first time. I still think it
should be faster than this, but I don't see a quick way to optimize,
right now.
=> Longer timeouts for first matrix sync

src/raiden_libs/service_registry.py, tests/libs/test_service_registry.py
A large collection of UI improvements for the service registration. Highlights:
* info command to show past deposits
* extend command to prolong registration
* no need to remember your deposit address, `withdraw` will find it for you
Closes https://github.com/raiden-network/raiden-services/issues/768 and https://github.com/raiden-network/raiden-services/issues/490.
=> Improve registry script usability

.bumpversion.cfg, CHANGELOG.md, Dockerfile, docs/conf.py, setup.py
Changes included:
* Improve registration script ([#890](https://github.com/raiden-network/raiden-services/pull/890)) to allow for extension.
* Longer timeouts for first Matrix sync ([#878](https://github.com/raiden-network/raiden-services/pull/878)).
* Adaptions for newer Matrix usage in Raiden.
* Dependency updates.
=> Prepare release 0.13.2

requirements.txt, src/raiden_libs/matrix.py, src/raiden_libs/utils.py, src/request_collector/cli.py, tests/libs/test_matrix.py
This PR is implementing #897 . I modified the WIP of #896 a bit and is to be continued in this PR since @ezdac is on vacation. 
The PFS creates a client for each homeserver in the list and listens on the presence events of each. Since we know that the presence of a user is always correct on their respective homeserver, presences are filtered by the homeservers.
All presences of Homeserver01 will be fetched by the sync of homeserver01 and so on...
This gracefully works around the present bug which happens to occur on forwarding presences due out the federation.
=> listen on presence by respective homeserver

Makefile
Eth packages have an circular dependency which are not compatible to each other. the new dependency resolver will not finish the installation.
=> Use legacy resolver until eth circular dependency is fixed

src/pathfinding_service/service.py, src/raiden_libs/matrix.py, src/raiden_libs/utils.py, src/request_collector/server.py, tests/libs/test_matrix.py
This PR introduces the ClientManager which controls the status of matrix clients to their respective home server. Each home server has a `connect_client_worker` which will trigger the creation of a new client if the connection to the homeserver fails. 
A reconnect is described by creating a new client object, logging into the server, joining broadcast rooms and starting the greenlet `listen_forever`.
=> Forever reconnect to other clients upon failure

src/pathfinding_service/service.py, src/raiden_libs/matrix.py, src/raiden_libs/utils.py, tests/pathfinding/test_service.py
This is alternative 2 from the discussion in #910 .
Instead of tracking presences by a channel open event, presences are being tracked once we receive a presence update from any user in the global room.
We assume that any user in the global room is a raiden user and will eventually create or already has created at least one channel.
In the future, spamming prevention should be set in place. We assume that spamming a global room will first result in a DoS attack against the server before it hits the PFS.
In order to hold the UserAddressManager in a reasonable size, any `leave` event for a user from a global room (which is effectively a user being purged due to 2 days of inactivity) could be used to untrack the address. This is an optimization and not part of the PR currently.
depends on: …
=> Track address by presence updates

src/pathfinding_service/service.py, src/raiden_libs/matrix.py, src/request_collector/server.py, tests/libs/test_matrix.py
Now the MatrixListener's sync-handler will also dispatch
to_device messages without an associated room to the message handler.
The message handler now also supports messages without an associated
room in it's call signature, while the message handling
does not need to be changed.
Resolves #914
We now switch to to-device communication for node-to-service
updates that were formerly handled by the respective service broadcast
room.
The services transport thus don't listen to messages in broadcast
rooms anymore and will only join the global discovery room
in order to still track user presences.
The sync message-handler ignores room messages and will only process
to-device messages.
The sync filter will ignore the discovery room messages for all matrix
clients of the services.
Resolves #915 …
=> Change MatrixListener to only accept `to_device` messages

src/pathfinding_service/exceptions.py, src/pathfinding_service/model/token_network.py, src/pathfinding_service/typing.py, tests/pathfinding/test_api.py, tests/pathfinding/test_graphs.py, tests/pathfinding/utils.py
I'm using the protected `_address_to_userids` to make this work. It
would make sense to provide a public way to get this information during
a future refactoring.
Closes https://github.com/raiden-network/raiden-services/issues/928
=> Include matrix user ids in route response

src/pathfinding_service/model/token_network.py, src/raiden_libs/logging.py, tests/libs/test_service_registry.py
I relied on my autoimporter, but that apparently messed up in a smart
enough way to fool CI.
=> Fix bad imports from `src`

src/pathfinding_service/model/token_network.py, tests/pathfinding/test_api.py
Returning a mapping instead of a list should make this more pleasant to
use in the client.
=> Return matrix user ids in dict

src/pathfinding_service/api.py, src/pathfinding_service/exceptions.py, src/pathfinding_service/model/token_network.py, src/pathfinding_service/typing.py, tests/pathfinding/test_api.py, tests/pathfinding/utils.py
This PR adds an endpoint where the PFS returns a `user_id` for a given address if this user is online derived from synapse's presence state. If there is no user online then a `404` will be returned.
This endpoint is specifically going to be used for direct payments but can also be used for other use cases.
There are additional minor fixes in the tests as they did not use the correct interface for `get_user_ids_for_address` in the user manager as well irregular matrix user ids. 
fixes: #930
=> Add endpoint user

.bumpversion.cfg, CHANGELOG.md, Dockerfile, docs/conf.py, requirements.txt, setup.py, src/monitoring_service/cli.py, src/pathfinding_service/cli.py, src/raiden_libs/cli.py, src/raiden_libs/logging.py
This sets up the version for a new release `0.14.1`
Patch changes:
- This fixes an issue when setting up `sentry`, where the gevent threading module monkeypatching wasn't completed, while the `sentry` setup already generated log events with thread logging enabled.
- This also removes a patch from the DNS resolver, that lead to problems when trying to resolve addresses from a VPN NS from within docker.
- Furthermore, the `raiden` dependency, formerly linked to the `develop` at github, is now linked to a specific commit. This is done to remove version ambiguity for the next release of `raiden-services`.
=> Release 0.14.1: Disable thread logging, reset resolver settings, pin raiden

src/pathfinding_service/api.py, src/pathfinding_service/model/token_network.py, src/pathfinding_service/typing.py, tests/pathfinding/test_api.py, tests/pathfinding/utils.py
This PR adds capabilities to the address metadata
It also renames the endpoint to `/v1/address/<checksummed_address>/metadata`. 
The return value in case of success looks like
```
{"user_id": <user_id>, "capabilities": <capabilities>}
```
Its the simplistic consistent approach to have capabilities somewhat fetchable from the PFS. It needs to be sorted out whether , how and when these information are actually necessary. 
Also the route metadata information are renamed to `address_metadata` and come in the format 
```
{<address>: {"user_id": <user_id>, "capabilities": <capabilities>}}
```
Maybe this could be defined as its own type in the Raiden client and then be used by the services.
fixes: #939
=> add capabilities to address_metadata_endpoint

deployment/docker-compose.yml
Since https://github.com/raiden-network/raiden-services/pull/951, we can
use the unstable contracts environment. We want to do that for the
development machines that are run using the docker-compose. Since that
environment only exists for goerli, we only enable it for the goerli
services.
Relates to https://github.com/raiden-network/light-client/issues/2521
=> Use unstable contract env for goerli docker setup

src/raiden_libs/matrix.py, tests/libs/test_matrix.py
there was a `RaidenUnrecoverableError` uncaught from join_broadcast_room. I removed the call and joined directly by the `client.join_room` call
=> fix uncaught error in connecting to matrix server

src/raiden_libs/matrix.py
The failing scenarios described in [SP failure: lock expired](https://github.com/raiden-network/scenario-player/issues/667) were partly due to an unhandled exception in the PFS causing the PFS to stop syncing with a homeserver.
The bug happens when a server is currently unavailable and returning a `404` during `sync`. This happens when a Matrix server restarts. While the Matrix API translates this request error to a `MatrixRequestError`, [`GMatrixClient.listen_forever()`](https://github.com/raiden-network/raiden/blob/6455900101bdadade572689e83170b3a55ebc283/raiden/network/transport/matrix/client.py#L387) only handles `MatrixRequestError` when `error_code >= 500`. A `404` will be raised again and thrown back. This was an unhandled edge case in …
=> fix unhandled MatrixRequestError in PFS

src/raiden_libs/user_address.py, tests/pathfinding/test_api.py, tests/pathfinding/utils.py
Capabilities are returned as a dictionary in the AddressMetadata. To comply with the outer representation in the matrix profile as well, we could comply and also pass the capabilities as the avatar_url string
=> Return user capabilities as url

src/raiden_libs/events.py
Python dataclasses inheritance can't mix between frozen and non-frozen classes.
There was a bug in Python that skipped this check for base classes without fields.
We benefited from this bug since the `raiden_libs.events.Event` base-class is non-frozen, yet the derived classes in `monitoring_service.events` are.
The [bug got fixed](https://bugs.python.org/issue43176) and the fix released in Python 3.8.10 and 3.9.5.
This causes our current usage to break with a TypeError.
Luckily, since we don't use any dataclass specific features on the base-class, we can simply remove the `@dataclass` decorator from it.
=> Make `Event` base class a non dataclass

src/pathfinding_service/api.py, src/raiden_libs/user_address.py, tests/pathfinding/test_api.py, tests/pathfinding/utils.py
Closes #991 
Adding `last_seen` information to offline nodes. This will help the decision to delete inactive nodes.
=> Add last_seen data to offline nodes

src/pathfinding_service/api.py, tests/pathfinding/test_api.py, tests/pathfinding/utils.py
This makes it possible to run the Raiden explorer efficiently.
Closes https://github.com/raiden-network/raiden-services/issues/1007.
=> Add endpoint to return all online addresses

src/pathfinding_service/api.py, src/raiden_libs/cli.py, src/raiden_libs/user_address.py
Fixes https://github.com/raiden-network/raiden/issues/7043
The original idea was to replace the usage of naive datetime with timezone aware timestamps, but since the code seems to [actively reject](https://github.com/netcriptus/raiden-services/blob/master/src/pathfinding_service/service.py#L341) the use of the proposed format, and the reason is unclear, for now I'll just make sure all timestamps being used are coming from `utcnow` instead of just `now`.
=> use utcnow everywhere

src/raiden_libs/matrix.py
This fixes #1023.
Optionally override the default matrix known server urls, if
the environment variable
URL_KNOWN_FEDERATION_SERVERS
is given. This is common in RSB deployments, especially in testnet
deployments.
=> Read env var for known_servers

deployment/docker-compose.yml
This allows the MS to run, so that we can have successful scenarios on
rinkeby, too.
=> Register the MS for rinkeby

src/pathfinding_service/api.py, tests/pathfinding/test_api.py
#961 turned out harder than necessary to debug (nothing to find in log). This PR adds some logging in those cases.
=> Add debug log when discarding IOUs

.github/workflows/update_latest_image.yml
Docker hub doesn't build images on demand any more without a paid subscription. So lets do this stuff by hand 😩 
This image is used by the `services-dev` server which runs he nightly services.
=> Build latest image in actions

src/pathfinding_service/model/token_network.py, src/pathfinding_service/service.py, tests/pathfinding/test_service.py, tests/pathfinding/test_token_network.py
Fixes https://github.com/raiden-network/raiden-services/issues/1040
Handle `ChannelSettled` events in the PFS. This wasn't necessary before, as there was always a `ChannelClosed` event emitted. But with cooperative settlement a single `ChannelSettled` might be emitted and must be handled.
=> PFS: handle settled events for coop settle

src/pathfinding_service/api.py, src/raiden_libs/blockchain.py, tests/pathfinding/test_payment.py
Remove RPC calls to get block number for IOU check, since these can be slow and we keep our block number up to date in the DB.
Also reduce number of RPC calls to UDC.getEffectiveBalance to increase performance. There are schemes that are both faster and slightly safer than this approach, but this is good simple tradeoff for now.
=> Less RPC calls in IOU check

src/monitoring_service/handlers.py, src/raiden_libs/blockchain.py
- Fix upper bound of `get_pessimistic_udc_balance`
- some minor improvements to remove temporary variables
=> Fix upper bound for `get_pessimistic_udc_balance`

requirements.txt
Get rid of pinned git commits in the dependencies.
Fixes #938
=> Use released versions instead of git commits

.codecov.yml, src/raiden_libs/user_address.py
Before, the whitelisting mechanism of the services had a bug:
Several `__getitem__` calls meant to be **readonly**  to the internal defaultdict that tracks the whitelisted user-addresses were unintentionally causing the address being added to the dict with a default-value.
This in the end let the address pass the whiltelisting check:
https://github.com/raiden-network/raiden-services/blob/091c6ca8d18c0cc7b58f407ed7847c89a89fb338/src/raiden_libs/user_address.py#L311-L312
Which can potentially lead to performance issues and heavy load on the matrix servers.
This PR fixes this issue.
=> Fix unintentional creation of defaultdict key by __getitem__ calls

docs/index.rst, src/monitoring_service/exceptions.py, src/monitoring_service/handlers.py, src/monitoring_service/service.py, src/pathfinding_service/claim_fees.py, src/raiden_libs/database.py, tests/monitoring/monitoring_service/test_end_to_end.py, tests/monitoring/monitoring_service/test_service.py
=> Reschedule too early events

src/monitoring_service/cli.py, src/pathfinding_service/cli.py
Follow up on #1154
When the user does not manually define a number of confirmation blocks for the PFS or MS and the chain is detected to be Arbitrum, it will automatically set the number to zero. On Arbitrum based chains there are no confirmation blocks necessary.
=> add automatic adaption of confirmations blocks

requirements.txt, src/raiden_libs/cli.py
Closes #1162 
The parser for the gas price parameter has become extended with a new price strategy. This 'rpc' strategy is especially important to run the RSB for Arbitrum networks.
=> add support for the new 'rpc' gas price
