raiden-network/raiden-services

.flake8
.gitignore
.isort.cfg
.travis.yml
Makefile
libs/.coveragerc
libs/requirements-dev.txt
monitoring/requirements-dev.txt
pathfinding/pathfinding_service/cli.py
pathfinding/pathfinding_service/model/token_network.py
pathfinding/pathfinding_service/tests/conftest.py
pathfinding/pathfinding_service/tests/test_cli.py
pathfinding/pathfinding_service/tests/test_rest.py

This sets up basic CI and coverage.

CI & coverage setup

---

pathfinding/pathfinding_service/config.py
pathfinding/pathfinding_service/model/channel_view.py
pathfinding/pathfinding_service/model/token_network.py
pathfinding/pathfinding_service/service.py
pathfinding/pathfinding_service/tests/fixtures/network_service.py
pathfinding/pathfinding_service/tests/test_blockchain_integration.py
pathfinding/pathfinding_service/tests/test_blockchain_listener.py
pathfinding/pathfinding_service/tests/test_graphs.py
pathfinding/pathfinding_service/tests/test_mocked_integration.py

Adds settle_timeout & reveal_timeout to pfs's channel view

---

pathfinding/pathfinding_service/config.py
pathfinding/pathfinding_service/model/token_network.py
pathfinding/pathfinding_service/service.py
pathfinding/pathfinding_service/tests/fixtures/network_service.py
pathfinding/pathfinding_service/tests/test_blockchain_integration.py
pathfinding/pathfinding_service/tests/test_graphs.py
pathfinding/pathfinding_service/tests/test_mocked_integration.py
pathfinding/pathfinding_service/tests/test_rest.py

Adds settle & reveal timeout to path finding - incl. tests

---

.travis.yml
requirements.txt
setup.py
src/monitoring_service/handlers.py

Remove support for python 3.6

---

src/raiden_libs/messages/json_schema.py
src/raiden_libs/messages/monitor_request.py
src/raiden_libs/test/fixtures/address.py
src/request_collector/state_db/sqlite_db.py
tests/libs/test_messages.py
tests/monitoring/fixtures/monitor_request.py

Remove unused monitor_addres from MR

---

tests/monitoring/fixtures/server.py

by reusing the raiden_service_bundle fixture from raiden-contracts.

Simply monitoring service fixture

---

src/raiden_libs/test/fixtures/address.py

Remove unused fixture

---

tests/monitoring/fixtures/server.py
tests/monitoring/monitoring_service/test_end_to_end.py

See https://github.com/raiden-network/raiden-contracts/issues/480

Fix tests after rename of RSB in contracts

---

src/monitoring_service/handlers.py
src/monitoring_service/states.py
tests/monitoring/monitoring_service/test_end_to_end.py
tests/monitoring/monitoring_service/test_handlers.py

Handle updates

---

Makefile
src/monitoring_service/events.py
src/monitoring_service/handlers.py
src/raiden_libs/messages/message.py
src/raiden_libs/test/mocks/client.py
src/raiden_libs/transport/transport.py
src/request_collector/state_db/sqlite_db.py
tests/libs/conftest.py
tests/libs/fixture_overwrites.py
tests/libs/test_client_mock.py
tests/libs/test_messages.py
tests/libs/test_utils.py
tests/monitoring/conftest.py
tests/monitoring/monitoring_service/test_end_to_end.py
tests/monitoring/monitoring_service/test_handlers.py
tests/pathfinding/fixtures/accounts.py
tests/pathfinding/fixtures/network_service.py
tests/pathfinding/test_graphs.py
tests/pathfinding/test_mocked_integration.py
tests/pathfinding/test_rest.py

3 errors remain, but will be solved this week when files are changed

Adds tests to makefile and resolves most make lint errors

---

README.md

Add basic information to the README

---

README.md

Link docs in REAME

---

tests/monitoring/monitoring_service/test_handlers.py

Add test for MR received before ChannelOpen event

---

src/monitoring_service/handlers.py
tests/monitoring/monitoring_service/test_handlers.py

Add test for `monitor` being called after ActionMonitoringTriggeredEvent

---

.dockerignore
Dockerfile

Add .dockerignore and update Dockerfile for PFS

---

src/pathfinding_service/cli.py

Add POA middleware to make PFS run on POA test chains

---

src/monitoring_service/blockchain.py
tests/monitoring/monitoring_service/test_blockchain.py
tests/monitoring/monitoring_service/test_end_to_end.py

Add a test for the assumption and simplify the code a bit according to that.

Test event filtering boundaries and simplify limit calculation in BC listener

---

tests/monitoring/monitoring_service/test_handlers.py

Add handler tests

---

.bumpversion.cfg
requirements-dev.txt

Add bumpversion

---

requirements.txt
src/monitoring_service/cli.py
src/request_collector/cli.py
tests/monitoring/fixtures/server.py
tests/monitoring/monitoring_service/test_cli.py
tests/monitoring/request_collector/test_cli.py
tests/pathfinding/test_rest.py

Use keystore file instead of raw private key

---

src/monitoring_service/database.py
src/monitoring_service/schema.sql
src/monitoring_service/service.py
src/raiden_libs/test/mocks/client.py
tests/monitoring/monitoring_service/test_crash.py
tests/monitoring/monitoring_service/test_end_to_end.py

Add test for MS crash handling

---

src/monitoring_service/cli.py
tests/monitoring/fixtures/server.py
tests/monitoring/monitoring_service/test_cli.py

These need to be set properly.

Remove default contract addresses and make them required

---

src/monitoring_service/database.py
src/monitoring_service/states.py
src/request_collector/server.py
tests/monitoring/request_collector/test_server.py
tests/pathfinding/test_blockchain_listener.py

Also fix some bytes/hex encoding issues.
Closes #115.

Compare nonce when accepting new MR

---

src/request_collector/cli.py
src/request_collector/matrix.py
src/request_collector/server.py
tests/monitoring/fixtures/server.py

We need to start the matrix listeners event loop.
However, this solutions still feels rough and probably can be improved.

Start the GMatrixClients event loop

---

src/monitoring_service/cli.py
src/raiden_libs/logging.py
src/request_collector/cli.py
tests/monitoring/monitoring_service/test_cli.py
tests/monitoring/request_collector/test_cli.py

Convert request collector to structlog

---

src/raiden_libs/matrix.py
src/request_collector/server.py

Fixes #117 and logs more info.

User caching

---

src/pathfinding_service/api/rest.py
src/pathfinding_service/cli.py
src/pathfinding_service/model/token_network.py
src/pathfinding_service/service.py
src/pathfinding_service/utils/blockchain_listener.py
src/raiden_libs/logging.py
tests/pathfinding/test_cli.py

Convert PFS to structlog

---

requirements-dev.txt
tests/pathfinding/test_cli.py

Fixes https://github.com/raiden-network/raiden-services/issues/108

Fix cli tests with structlog

---

deployment/.gitignore
deployment/builder/Dockerfile
deployment/builder/app/main.py
deployment/builder/app/requirements.txt
deployment/config/traefik/traefik.toml
deployment/docker-compose.override.yml
deployment/docker-compose.yml
deployment/services.env
deployment/update.sh
src/pathfinding_service/cli.py

Merge https://github.com/palango/services-dev into this repo.
* add containers for MS and RC
* use single image for all containers
* provide `docker-compose.override.yml` for local testing
* reuse shared args via yaml merge command
* use keystore (which is now required for all services)
Closes #22

Add Continuous Deployment code to this repo

---

src/monitoring_service/handlers.py
src/monitoring_service/service.py
tests/monitoring/monitoring_service/test_handlers.py

Check transactions receipts for errors

---

src/monitoring_service/database.py
src/monitoring_service/handlers.py
src/monitoring_service/schema.sql
src/monitoring_service/service.py
tests/monitoring/monitoring_service/test_handlers.py

@karlb Can you have a first look on if this looks reasonable
Part of #157

Store waiting transactions in DB

---

src/monitoring_service/database.py
src/monitoring_service/handlers.py
tests/monitoring/monitoring_service/test_database.py
tests/monitoring/monitoring_service/test_handlers.py

Idempotent scheduled events

---

src/monitoring_service/service.py

To limit the log output a bit.

Show number of scheduled events after event processing

---

src/monitoring_service/handlers.py
tests/monitoring/monitoring_service/test_handlers.py

Also add some tests for the whole action_claim_reward_triggered_event_handler

Check reward before calling claimReward

---

src/monitoring_service/cli.py
src/pathfinding_service/cli.py
src/pathfinding_service/service.py
src/raiden_libs/contract_info.py
tests/libs/test_contract_info.py
tests/pathfinding/test_cli.py

Fixes #153 
The PFS cli tests still need some work, but have a look if you like the general approach.

Get contract addresses from deployment info by default

---

src/raiden_libs/test/fixtures/web3.py

This cuts our test runtime by 30%!

Fix gas estimation to a high constant in tests

---

src/monitoring_service/cli.py
src/monitoring_service/handlers.py
src/monitoring_service/service.py
tests/monitoring/monitoring_service/test_handlers.py

Adds option for minimum required service fee for ms

---

src/pathfinding_service/api/rest.py
src/pathfinding_service/cli.py
src/pathfinding_service/config.py
src/pathfinding_service/exceptions.py
src/pathfinding_service/service.py
tests/pathfinding/fixtures/network_service.py
tests/pathfinding/test_blockchain_integration.py
tests/pathfinding/test_payment.py

Closes https://github.com/raiden-network/raiden-services/issues/177

Check UserDeposit contract when accepting PFS fees

---

requirements.txt
setup.py
src/pathfinding_service/exceptions.py
src/pathfinding_service/model/channel_view.py
src/pathfinding_service/model/token_network.py
src/pathfinding_service/service.py
tests/pathfinding/test_capacity_updates.py

Adds Capacity Updates and tests to pfs

---

requirements.txt
setup.py
src/raiden_libs/contract_info.py

and stop calling get_contracts_deployed() twice.

Upgrade raiden-contracts to 0.16.0

---

scenarios/scenario_ms_monitor_and_claim.yml

Fixes #181 
Fixes #122 
Fixes #31

Adds integration test scenario

---

src/pathfinding_service/service.py
src/raiden_libs/matrix.py

It's really strange that this stuff wasn't found by mypy. I guess we should look into #167 soon.

Fix problems in on_pfs_update

---

requirements-dev.txt
requirements.txt
setup.py

Sync some updates on the raiden side.

Update versions to latest raiden version

---

README.md
src/monitoring_service/cli.py
src/pathfinding_service/cli.py
src/pathfinding_service/service.py
src/raiden_libs/cli.py
src/request_collector/cli.py

Make the CLIs more consistent and fix `--help` to work without giving a password.

Cli improvements

---

docs/index.rst

@czepluch @karlb Please give this a look, I don't think we need to go into more detail yet.
Fixes #193

Add docs for installation and running the services.

---

src/monitoring_service/blockchain.py
tests/monitoring/monitoring_service/test_states.py

When https://github.com/raiden-network/raiden-contracts/pull/813 gets
merged we need this changes to avoid mypy errors.

Fix typing after using types from raiden-contracts

---

requirements-dev.txt

Up to 4x faster 🎉 
https://mypy-lang.blogspot.com/2019/04/mypy-0700-released-up-to-4x-faster.html

Upgrade to latest mypy (0.700)

---

docs/index.rst
setup.py
src/pathfinding_service/claim_fees.py
src/pathfinding_service/database.py
src/pathfinding_service/model/iou.py
src/pathfinding_service/schema.sql
tests/pathfinding/test_claim_fees.py

Closes https://github.com/raiden-network/raiden-services/issues/151.

Provide CLI script to claim earned PFS fees

---

Makefile
pylintrc
requirements-dev.txt
src/monitoring_service/blockchain.py
src/monitoring_service/events.py
src/monitoring_service/service.py
src/pathfinding_service/blockchain.py
src/pathfinding_service/claim_fees.py
src/pathfinding_service/exceptions.py
src/pathfinding_service/model/token_network.py
src/pathfinding_service/service.py
src/raiden_libs/matrix.py
src/request_collector/server.py
tests/libs/fixtures/client.py
tests/libs/mocks/client.py
tests/libs/mocks/test_client_mock.py
tests/monitoring/monitoring_service/test_crash.py

The category "good checks that could be enabled in the future" in
pylintrc should be worked through at some point.

Run pylint with many checks turned off

---

src/pathfinding_service/claim_fees.py
src/raiden_libs/cli.py

I also think this is nicer to read and more flexible than before.
Closes #228.

 Make order of `keystore` and `password` irrelevant 

---

src/pathfinding_service/service.py

Log more infos when `UpdatePFS` messages are received.

Small logging improvements for PFS update messages

---

.codecov.yml
src/monitoring_service/blockchain.py
src/monitoring_service/service.py

There's no need to have a `BlockchainListener` class when a freestanding funcion works as well. Even `pylint` tells us that 😄

Switch blockchain listener into freestanding function

---

src/monitoring_service/cli.py
src/monitoring_service/service.py
src/pathfinding_service/claim_fees.py
src/pathfinding_service/cli.py
src/pathfinding_service/service.py
src/raiden_libs/cli.py
src/raiden_libs/contract_info.py
tests/libs/test_contract_info.py
tests/monitoring/fixtures/server.py
tests/monitoring/monitoring_service/test_cli.py
tests/monitoring/monitoring_service/test_crash.py
tests/pathfinding/fixtures/network_service.py
tests/pathfinding/test_blockchain_integration.py
tests/pathfinding/test_claim_fees.py
tests/pathfinding/test_cli.py

I didn't get as far as I wanted, but I have to wrap it up for now to get some of the "real" tickets done.

Refactor handling of blockchain args in CLI and constructors

---

requirements.txt
setup.py
src/pathfinding_service/config.py
src/pathfinding_service/model/channel_view.py
src/pathfinding_service/model/token_network.py
src/pathfinding_service/service.py
src/raiden_libs/contract_info.py
tests/pathfinding/fixtures/network_service.py
tests/pathfinding/test_capacity_updates.py
tests/pathfinding/test_graphs.py

Updates raiden commit and store the mediation fee info.
Fixes #233

Receive and store fee info in PFS

---

src/pathfinding_service/model/channel_view.py
src/pathfinding_service/model/token_network.py
tests/pathfinding/fixtures/network_service.py

Use specialized types in ChannelView

---

requirements.txt
setup.py
src/pathfinding_service/cli.py

Update to latest raiden and contracts.

Update contracts and raiden commit

---

docs/index.rst

Fix installation instructions

---

pylintrc
src/pathfinding_service/api.py

Enable pylints no-else-return

---

tests/pathfinding/test_capacity_updates.py

Cleanup tests

---

src/monitoring_service/database.py
src/monitoring_service/handlers.py
src/monitoring_service/service.py
src/pathfinding_service/claim_fees.py
src/pathfinding_service/database.py
src/pathfinding_service/model/channel_view.py
src/pathfinding_service/model/token_network.py
src/pathfinding_service/schema.sql
src/pathfinding_service/service.py
src/raiden_libs/database.py
src/raiden_libs/events.py
tests/libs/fixtures/__init__.py
tests/libs/fixtures/cli.py
tests/libs/fixtures/web3.py
tests/libs/mocks/web3.py
tests/monitoring/fixtures/server.py
tests/monitoring/monitoring_service/test_crash.py
tests/pathfinding/fixtures/network_service.py
tests/pathfinding/test_claim_fees.py
tests/pathfinding/test_graphs.py
tests/pathfinding/test_service.py

Closes #10.
There' some refactoring work left for the `BlockchainState`, but that can be done in a different PR.

Save and load state in PFS

---

src/pathfinding_service/api.py
src/pathfinding_service/exceptions.py
tests/pathfinding/test_rest.py

 Refactor error handling in `paths` endpoint

---

adr/001-update-pfs-message.md

@Dominik1999 I started writing the `UpdatePFS`  ADR. If you find time feel free to continue, otherwise I'll finish this next week.
Fixes #227

Initial work on UpdatePFS design ADR

---

tests/pathfinding/test_capacity_updates.py

Improve capacity updates tests

---

src/pathfinding_service/api.py
tests/pathfinding/test_rest.py

Report correct fee in info endpoint

Report correct fee in info endpoint

---

src/monitoring_service/service.py
src/pathfinding_service/service.py
src/raiden_libs/gevent_error_handler.py
src/request_collector/server.py

Closes https://github.com/raiden-network/raiden-services/issues/269.

 Do not ignore system errors and unfiy error handling

---

scenarios/simple_pfs_integration_without_reward.yml

Changes the pfs scenario to a running scenario

---

Dockerfile
deployment/builder/Dockerfile
deployment/builder/app/main.py
deployment/docker-compose.override.yml
deployment/docker-compose.yml
deployment/services.env
deployment/update.sh

Update the deployment configs to work with the latest PFS changes.
Part of #284

Update deployment config

---

deployment/docker-compose.override.yml

Further deployment fixes

---

deployment/builder/app/main.py
deployment/docker-compose.yml

This should fix the builder update process.

Correctly mount directories for builder

---

src/pathfinding_service/api.py

Closes a minor bug regarding IOU acceptance, addresses were checked but the check failed for same addresses if one was not checksummed.

uses better address comparison (checksum-agnostic) and adds some logs

---

deployment/builder/app/main.py

- Stop all containers art the same time
- Format builder code with `black`

Deployment: Stop all containers at the same time

---

tests/pathfinding/fixtures/network_service.py
tests/pathfinding/test_service.py

Add some tests for the event handlers in PFS service.

Test more edge cases in PFS service

---

src/pathfinding_service/model/iou.py
src/pathfinding_service/model/token_network.py
tests/pathfinding/fixtures/network_service.py
tests/pathfinding/test_capacity_updates.py

Fix annotation

---

tests/libs/test_matrix.py
tests/monitoring/monitoring_service/test_end_to_end.py

Start with increasing matrix coverage.
Part of #124

Add tests for matrix.message_from_dict

---

src/pathfinding_service/api.py
tests/pathfinding/test_api.py

We want to assert the sent and stored ious in the pfs via the scenario player

Adds debug endpoint for ious for scenario player

---

tests/monitoring/fixtures/server.py
tests/monitoring/monitoring_service/test_end_to_end.py

This improves coverage on some branches.

Fix MS e2e test to wait for ClaimReward event

---

src/raiden_libs/blockchain.py

- Remove some unnecessary conditions
- Cache topic_to_event_abi mapping, to safe some cycles
Also tested with parity and geth, both work fine.

Improve event decoding

---

src/monitoring_service/handlers.py
tests/monitoring/monitoring_service/test_handlers.py

Log useful infos when a ClaimReward event is received.

Claim event

---

adr/002-update-pfs-message.md

@Dominik1999 @karlb @konradkonrad 
A first draft of our discussion yesterday. Please have a look and tell me when I misunderstood something.
Closes #275

Draft ADR for feedback mechanism

---

pylintrc
src/monitoring_service/service.py
src/pathfinding_service/api.py
src/pathfinding_service/claim_fees.py
src/pathfinding_service/cli.py
src/pathfinding_service/middleware.py
src/pathfinding_service/model/token_network.py
src/pathfinding_service/service.py
src/raiden_libs/blockchain.py
src/raiden_libs/cli.py
src/raiden_libs/database.py
src/raiden_libs/gevent_error_handler.py
src/raiden_libs/matrix.py
tests/monitoring/monitoring_service/test_crash.py
tests/monitoring/monitoring_service/test_end_to_end.py
tests/pathfinding/fixtures/api.py
tests/pathfinding/fixtures/network_service.py
tests/pathfinding/test_api.py
tests/pathfinding/test_blockchain_integration.py
tests/pathfinding/test_capacity_updates.py
tests/pathfinding/test_claim_fees.py
tests/pathfinding/test_graphs.py
tests/pathfinding/test_middleware.py
tests/pathfinding/test_payment.py
tests/pathfinding/test_service.py

Relates to https://github.com/raiden-network/raiden-services/issues/280.

Enable more pylint checks

---

scenarios/Test_PFS_integration_with_reward.yml

Adds pfs scneario with payment

---

requirements-dev.txt

Just bring some deps up-to-date.

Update some dev dependencies

---

src/pathfinding_service/service.py
src/raiden_libs/blockchain.py
src/raiden_libs/cli.py

Fixes some logs, but logging for events became even worse.

Convert hex addresses to bytes when filtering events

---

src/pathfinding_service/database.py
src/pathfinding_service/model/channel_view.py
src/pathfinding_service/model/token_network.py
src/pathfinding_service/schema.sql
src/pathfinding_service/service.py
tests/pathfinding/fixtures/network_service.py
tests/pathfinding/test_capacity_updates.py

Adds minimum calculation for capacity updates

---

src/monitoring_service/database.py
src/monitoring_service/service.py
src/pathfinding_service/database.py
src/raiden_libs/database.py
tests/monitoring/fixtures/server.py

Adding `ChainID` and `ChannelID`

Small typing improvements

---

tests/pathfinding/fixtures/network_service.py
tests/pathfinding/test_graphs.py

Remove test_routing_benchmark

---

.codecov.yml

Let's fix the minimum coverage.

Fix minimum code coverage to 90%

---

src/pathfinding_service/database.py
src/pathfinding_service/model/__init__.py
src/pathfinding_service/schema.sql
tests/pathfinding/test_database.py

This adds the type FeedbackToken which will be used for the feedback
mechanism. It also adds code to save and load it from the database.
Part of #336

Add FeedbackToken

---

src/pathfinding_service/model/token_network.py
tests/pathfinding/test_graphs.py

Closes https://github.com/raiden-network/raiden-services/issues/321.

Include mediation fees in capacity check

---

src/pathfinding_service/model/token_network.py
tests/pathfinding/test_graphs.py

Adds edge weight for routes w/o capa for refunds

---

src/monitoring_service/service.py
src/pathfinding_service/service.py
src/raiden_libs/utils.py
tests/monitoring/monitoring_service/test_handlers.py
tests/monitoring/monitoring_service/test_states.py
tests/pathfinding/fixtures/accounts.py
tests/pathfinding/test_api.py
tests/pathfinding/test_capacity_updates.py
tests/pathfinding/test_payment.py

Fix public_key_to_address typing

---

requirements.txt
setup.py
src/pathfinding_service/config.py
src/pathfinding_service/model/feedback.py
src/pathfinding_service/model/token_network.py
src/pathfinding_service/service.py
src/raiden_libs/matrix.py
src/raiden_libs/utils.py
src/request_collector/server.py
tests/libs/test_matrix.py
tests/monitoring/request_collector/test_server.py
tests/pathfinding/fixtures/network_service.py
tests/pathfinding/test_blockchain_integration.py
tests/pathfinding/test_capacity_updates.py
tests/pathfinding/test_database.py
tests/pathfinding/test_graphs.py
tests/pathfinding/test_model.py
tests/pathfinding/test_service.py

Get and store presence information from raiden nodes and use them for routing.

Use Matrix presence information

---

src/request_collector/server.py

Forgot to update this when I changed the matrix client.
Again a bit surprising that none of the tools found that.

Fix RC after matrix changes

---

adr/003-mediation-fees.md

I've changed the proportional fee to a float value again, since we won't be 100% accurate anyway due to the interpolation of the imbalance penalty function.
Did I forget anything? Do any points need more clarification? Did I assume consensus on something we didn't agree on?
Closes https://github.com/raiden-network/raiden-services/issues/341.

Add mediation fees ADR

---

tests/pathfinding/test_graphs.py

Deduplicates get_paths in test_graphs

---

src/pathfinding_service/service.py

Ideally we would print addresses checksummed, but better than nothing for now.

Improve event logging in PFS

---

scenarios/scenario_ms_monitor_and_claim.yml

also
* switch from time to block numbers
* remove hard coded raiden executable

Update scenario to firstAllowedBlockToMonitor

---

src/pathfinding_service/model/token_network.py
tests/pathfinding/test_graphs.py

Skip presence check until #365 is fixed

---

src/raiden_libs/matrix.py

Log the current presence as well.

Log more infos about presence updates

---

src/pathfinding_service/database.py
src/pathfinding_service/model/channel_view.py
src/pathfinding_service/model/token_network.py
src/pathfinding_service/schema.sql
tests/pathfinding/test_capacity_updates.py
tests/pathfinding/test_fee_schedule.py
tests/pathfinding/test_graphs.py

This is the main work for https://github.com/raiden-network/raiden-services/issues/368. Accepting the UpdateFee messsage over the network is still left out. I'll add that in the next PR after having a look at Raiden's message handling after the dataclass PR and updating to the latest Raiden version.

Flexible mediation fee calculation

---

src/monitoring_service/database.py
src/monitoring_service/handlers.py
src/monitoring_service/states.py
src/raiden_libs/types.py
tests/monitoring/monitoring_service/factories.py
tests/monitoring/monitoring_service/test_database.py

Use clients TransactionHash type

---

src/pathfinding_service/model/token_network.py
src/raiden_libs/matrix.py
tests/pathfinding/test_graphs.py

Presence take2

---

pylintrc
src/pathfinding_service/exceptions.py
src/pathfinding_service/model/channel_view.py
src/pathfinding_service/model/token_network.py
src/pathfinding_service/service.py
tests/pathfinding/test_fee_schedule.py
tests/pathfinding/test_service.py

Relates to https://github.com/raiden-network/raiden-services/issues/368.

Mediation fee improvements

---

src/pathfinding_service/api.py
src/pathfinding_service/service.py
src/request_collector/server.py

Small logging additions
Ref #270

Small logging improvements

---

tests/pathfinding/test_cli.py

Enable test_bad_eth_client again

---

requirements.txt
setup.py
src/monitoring_service/states.py
tests/libs/test_matrix.py
tests/monitoring/monitoring_service/test_end_to_end.py
tests/monitoring/request_collector/test_server.py

Also change the requirements substitution in setup.py to regexes, so
that we don't have to put the raiden revision in two places.

Update `raiden` and `raiden-contracts`

---

src/pathfinding_service/api.py
src/pathfinding_service/database.py
src/pathfinding_service/schema.sql
tests/pathfinding/test_api.py
tests/pathfinding/test_database.py

Closes #383 
This only calculates basic information right now, but more detailed stats can be added when necessary.

Calculate basic routing stats from feedback

---

src/raiden_libs/cli.py

Adds chain-id and contract version to db name

---

src/monitoring_service/service.py
src/pathfinding_service/service.py
src/raiden_libs/logging.py

Changes logging of MS and PFS to human readable logs

---

deployment/docker-compose.yml
src/pathfinding_service/api.py
src/raiden_libs/cli.py

A mixed bag of small updates,  mostly deployment related.

Deployment updates

---

deployment/docker-compose.yml
src/raiden_libs/cli.py
src/request_collector/cli.py
tests/monitoring/request_collector/test_cli.py

Add chain id parameter to MSRC

---

deployment/docker-compose.yml

I have to start running docker locally before...

Fix deployment envvars

---

Dockerfile
deployment/docker-compose.yml
src/raiden_libs/cli.py

Also adapt docker files to add a user, which fixes #399

Store db files in user dir

---

Dockerfile
deployment/docker-compose.yml
deployment/services.env

Stuff still doesn't work and I don't have time for further investigation.

Rollback docker changes

---

src/pathfinding_service/database.py
src/raiden_libs/logging.py

Just make some code a bit nicer

Little cleanups

---

src/raiden_libs/matrix.py
tests/libs/test_matrix.py

Adds exception handling to deserialization

---

src/pathfinding_service/database.py
src/pathfinding_service/service.py
src/pathfinding_service/typing.py
tests/pathfinding/test_capacity_updates.py

Cap update for unconfirmed channels

---

src/monitoring_service/service.py
src/raiden_libs/cli.py

This tries to be a simplified version of https://github.com/raiden-network/raiden-services/pull/415, by assuming that each service release is fixed to a specific contracts version.

Use gas costs in gas.json (simplified)

---

requirements.txt
tests/pathfinding/fixtures/iou.py

I found an undocumented change about module structures.

Update raiden-contracts to 0.24.0

---

src/pathfinding_service/database.py
tests/pathfinding/test_database.py

Fix deserialisation of PFSCapacityUpdate messages

---

Makefile

Add deps installation targets to makefile

---

src/pathfinding_service/service.py

Also lower the log level of the CapacityUpdate message log

Add log message when FeeUpdate is received

---

src/monitoring_service/handlers.py

Closes https://github.com/raiden-network/raiden-services/issues/421.

Explain why attackers can't waste the MS's gas

---

.bumpversion.cfg
CHANGELOG.md
Makefile
docs/conf.py
requirements-dev.txt
requirements.txt
setup.py

Also updated the release procedure here: https://github.com/raiden-network/team/wiki/%5BWIP%5D-Making-releases#services

Release 0.1

---

src/pathfinding_service/model/token_network.py

Some additional log calls to make debugging #440 easier

Add more logging to path search

---

src/pathfinding_service/model/token_network.py

Add more logging about why paths are invalid

---

src/raiden_libs/logging.py
tests/pathfinding/test_service.py

Now also nested structures look nice

Recursivly prettify log messages

---

requirements.txt
tests/monitoring/monitoring_service/test_crash.py
tests/monitoring/monitoring_service/test_end_to_end.py
tests/pathfinding/test_blockchain_integration.py

Closes https://github.com/raiden-network/raiden-contracts/issues/1117

Update raiden and raiden-contracts

---

src/monitoring_service/database.py
src/monitoring_service/states.py
src/request_collector/server.py
tests/constants.py
tests/monitoring/fixtures/server.py
tests/monitoring/monitoring_service/factories.py
tests/monitoring/monitoring_service/test_crash.py
tests/monitoring/monitoring_service/test_database.py

Caused by e9110e2cf5ccb91b2e3e84e99164104c03478fa5 and
693c9701ed41b2a471df53af5dea311aee6335cd.

Fix recently introduced reward signature problems

---

src/raiden_libs/logging.py
tests/pathfinding/test_service.py

Minor fix for logging of events and messages.

Fix logging the event/message name

---

setup.py
src/raiden_libs/cli.py
src/raiden_libs/register_service.py

Fixes #447
I need to write tests for this too....

Add register-service script for testnet ServiceRegistry

---

src/raiden_libs/matrix.py
src/request_collector/server.py
tests/libs/test_matrix.py
tests/monitoring/request_collector/test_server.py

Catching exceptions on_handle_message

---

package/README.md

Updates the readme according to the feedback we got from our colleagues

Change package readme acc to feedback

---

requirements.txt
src/monitoring_service/states.py
src/pathfinding_service/database.py
src/pathfinding_service/model/token_network.py
src/pathfinding_service/service.py
src/pathfinding_service/typing.py
src/raiden_libs/logging.py
src/raiden_libs/matrix.py
src/request_collector/server.py
tests/libs/test_matrix.py
tests/monitoring/fixtures/factories.py
tests/pathfinding/fixtures/network_service.py
tests/pathfinding/test_capacity_updates.py
tests/pathfinding/test_database.py
tests/pathfinding/test_fee_schedule.py
tests/pathfinding/test_service.py

* Fix import for messages
* Replace InvalidProtocolMessage by SerializationError

Update to latest raiden version

---

deployment/docker-compose.yml

This restores the current deployment until other issues are fixed.

Restore deployment

---

src/monitoring_service/handlers.py

Adds logging when the MS scheduled for triggering monitor but didn't at the end

Adds logging in the triggering monitor situation

---

package/README.md

After feedback from our friends at DigitalVirtues

Changes readme again to add ETH_RPC endpoint example

---

deployment/docker-compose.yml

This led to the problems tonight.

Add back missing env_file declaration

---

requirements.txt
src/monitoring_service/states.py
tests/monitoring/fixtures/server.py
tests/monitoring/monitoring_service/test_end_to_end.py
tests/pathfinding/test_blockchain_integration.py

The raiden release is not ready yet, so I'm providing this for early
review to speed up the release process.
[skip ci]

WIP: Update to latest raiden and raiden-contracts

---

src/pathfinding_service/api.py
src/pathfinding_service/cli.py
src/pathfinding_service/config.py
tests/pathfinding/fixtures/api.py
tests/pathfinding/test_api.py

Set pfs-info infos via cli arguments

---

deployment/builder/app/main.py

Enable git pulling again, so we get up-to-date configs.

Update git repository in builder

---

tests/pathfinding/test_capacity_updates.py

Just some minor things PyCharm complained about.

Add more type annotations in `tesgt_capacity_updates.py`

---

src/raiden_libs/register_service.py
tests/libs/test_register_service.py

There should be an CLI test as well, but this requires so much mocking that I didn't dare to do it now.
Part of #452 
Fixes #491

Update `register_service` script and add some tests

---

src/pathfinding_service/model/channel_view.py

Format participants in channel view repr as hex

---

src/pathfinding_service/model/channel_view.py

Add channel id to ChannelView repr

---

deployment/builder/app/main.py

Otherwise stuff isn't updated and Nils runs into problems.

Restart builder as well when deploying services

---

src/monitoring_service/constants.py
src/monitoring_service/database.py
src/request_collector/server.py
tests/monitoring/request_collector/test_server.py

Closes https://github.com/raiden-network/raiden-services/issues/504.

Ignore MRs sent after the channel has been closed

---

.bumpversion.cfg
CHANGELOG.md
docs/conf.py
requirements.txt
setup.py

New release 2000

---

deployment/docker-compose.yml

This should at least restart them when they get stuck.

Add healthchecks to PFS deployments

---

tests/pathfinding/test_token_network.py

Adds a test for `prune_graph`.

Add test for `prune_graph`

---

deployment/docker-compose.yml

This reverts commit 333d8503ee5e54da4fd6b3acac67bf58a46fc394.

Revert "Add healthchecks to PFS deployments"

---

requirements.txt
tests/pathfinding/test_graphs.py
tests/pathfinding/test_service.py

Update to contracts 0.31.0

---

requirements.txt

To fix scenario player breakage.

Update to latest raiden

---

src/raiden_libs/matrix.py
tests/libs/test_matrix.py

Follow-up to https://github.com/raiden-network/raiden-services/pull/528 as it didn't fix the message deserialization.

Fix message deserialization

---

src/raiden_libs/matrix.py

Remove unused SERVICE_MESSAGES and VALID_MESSAGE_TYPES

---

src/pathfinding_service/model/channel_view.py
src/pathfinding_service/model/token_network.py

Improve fee schedule setting in channel view

---

src/monitoring_service/cli.py
src/monitoring_service/service.py
tests/monitoring/fixtures/server.py
tests/monitoring/monitoring_service/test_crash.py

Closes https://github.com/raiden-network/raiden-services/issues/540
unless @palango is able to show me that it is possible to waste gas of
unregistered services.

Check for MS registration on startup

---

src/monitoring_service/service.py

This makes it harder for attackers to take down a MS. Before, even
restarting would not have helped in many cases because the same Event
would have been retried forever. Now, events are discarded when they
throw an exception and the MS continues to run.
To make sure that we don't ignore real errors, the exceptions are logged
and sentry issues are created.
There are no tests for this because I did not see a simple enough way to
exercise this in a meaningful manner.

Catch exceptions in event handlers

---

src/pathfinding_service/api.py
tests/pathfinding/test_api.py

Closes https://github.com/raiden-network/raiden-services/issues/547

Enable CORS requests

---

src/pathfinding_service/model/channel_view.py
src/pathfinding_service/model/token_network.py
tests/pathfinding/test_fee_schedule.py

Fixes #535
Before we applied the proportional fee on the incoming amount twice,
without taking the incoming fee into account. This commit changes that
and adds tests.

Improve fee estimate

---

src/pathfinding_service/model/token_network.py
tests/pathfinding/test_fee_schedule.py

Merge after #536 
-  Add some logs when routes are returned
- Add flat fee compounding test

Minor impro

---

tests/pathfinding/test_fee_schedule.py

Adds two simple imbalance cases for now

Add simple tests for imbalance fee calculation

---

Makefile
requirements.txt
src/monitoring_service/database.py
src/monitoring_service/handlers.py
src/monitoring_service/states.py
src/request_collector/server.py
tests/monitoring/monitoring_service/factories.py
tests/monitoring/request_collector/test_server.py

Closes https://github.com/raiden-network/raiden-services/issues/555.

Update to latest Raiden and contracts

---

src/pathfinding_service/model/channel.py
src/pathfinding_service/model/token_network.py
tests/pathfinding/test_fee_schedule.py

Fixes #554 
It basically adds more tests, especially such for imbalanced channels. It also updates the calculations, so that they're in line with what we discussed.

Fix fee calculation when at channel balance limits

---

src/monitoring_service/cli.py

This allows using database helper functions, calling contracts and
manually calling handlers. This will come in handy from time to time.

Add an ipython debug shell to MS

---

.bumpversion.cfg
Dockerfile
docs/conf.py
requirements.txt
setup.py

Merge after #570 
This updates to the latest raiden packaged version and prepares to release a patch version with that.

Update raiden version

---

src/raiden_libs/matrix.py
tests/libs/test_matrix.py

Fix matrix server for nightly test

---

src/raiden_libs/matrix.py

Closes https://github.com/raiden-network/raiden-services/issues/575

Use production matrix servers when on mainnet

---

requirements.txt
setup.py
src/pathfinding_service/model/channel.py
src/pathfinding_service/model/token_network.py
tests/pathfinding/test_fee_schedule.py

This needs surprisingly little changes on the PFS side.

Update raiden and adapt to capped mediation fees

---

requirements-dev.txt
src/pathfinding_service/model/token_network.py
tests/pathfinding/test_api.py

This now checks string formatting as well.

Update mypy to 0.740.0

---

requirements.txt

to work around https://github.com/raiden-network/raiden/issues/5122

Downgrade to raiden-contracts 33.1

---

src/pathfinding_service/api.py
tests/pathfinding/test_api.py

Closes https://github.com/raiden-network/raiden-services/issues/590

Show contracts version in info endpoint

---

requirements-dev.txt
tests/monitoring/monitoring_service/test_crash.py
tests/pathfinding/test_cli.py
tests/pathfinding/test_service.py

Closes https://github.com/raiden-network/raiden-services/issues/588

Fix flaky tests

---

src/pathfinding_service/constants.py
src/pathfinding_service/service.py
src/raiden_libs/constants.py
src/request_collector/server.py

Wait for matrix startup in RC

---

deployment/docker-compose.yml

This will persist logs and not loose them on restart

Use journald logging driver for deployment

---

src/raiden_libs/matrix.py
tests/libs/test_matrix.py

The MS/PFS iterates through all available servers and joins all PFS/MS rooms.
If no rooms are found, it creates the rooms.
Fixes #600, #601

Changes join_global_room to join_global_rooms.

---

requirements.txt

We want the more accurate fee calculation from
https://github.com/raiden-network/raiden/pull/5197.

Update raiden to include `Fraction` usage

---

src/raiden_libs/logging.py

Increase urllib3 log level to hopefully get more information about the matrix problems.
Related #616

Increase urllib3 log level

---

deployment/docker-compose.yml
src/raiden_libs/logging.py

This hopefully solves matrix rate limiting issues as seen in #615
Fixes #616

Fix startup order

---

requirements.txt
src/raiden_libs/cli.py

Update sentry to 0.13.1

---

requirements.txt
tests/pathfinding/test_api.py

Currently only a failing test that reproduces the error seen in #620

Add test case for #620

---

README.md

Fixes #580 
Update the link to the Raiden Service Bundle.

Fix link to RSB repo

---

src/pathfinding_service/cli.py
src/pathfinding_service/service.py
src/raiden_libs/matrix.py
src/request_collector/cli.py
src/request_collector/server.py

Closes https://github.com/raiden-network/raiden-services/issues/633

Allow setting the matrix servers via CLI

---

src/pathfinding_service/service.py

Don't force presence update when receiving capacity update

---

requirements.txt
tests/pathfinding/test_token_network.py

Regression test for
https://github.com/raiden-network/raiden-services/issues/636.

Add regression test for `x_list must be in str...`

---

src/pathfinding_service/service.py
tests/pathfinding/test_blockchain_integration.py

This is not solving a specific problem, but the changes are simple and should be an improvement.

PFS performance logging and tweaks

---

requirements.txt
src/pathfinding_service/constants.py
src/pathfinding_service/model/channel.py
src/pathfinding_service/model/token_network.py
src/raiden_libs/events.py
tests/monitoring/monitoring_service/factories.py
tests/monitoring/monitoring_service/test_crash.py
tests/monitoring/monitoring_service/test_handlers.py
tests/pathfinding/fixtures/network_service.py
tests/pathfinding/test_capacity_updates.py
tests/pathfinding/test_database.py
tests/pathfinding/test_fee_schedule.py
tests/pathfinding/test_graphs.py
tests/pathfinding/test_service.py
tests/pathfinding/test_token_network.py

See https://github.com/raiden-network/raiden/commit/1723377b982aabaa61318db3d8dffa9357b6a828

Use stricter type for reveal_timeout, settle_timeout

---

requirements.txt

Pulls the fix for https://github.com/raiden-network/raiden/issues/5389

Pull latest raiden develop branch

---

requirements.txt
src/pathfinding_service/cli.py
src/pathfinding_service/service.py
src/raiden_libs/matrix.py
tests/libs/test_matrix.py
tests/pathfinding/test_cli.py

Otherwise, we'll return "no route found" errors for a while because the presence is still missing.
Closes #658

Wait for first matrix sync before starting PFS API

---

src/pathfinding_service/model/token_network.py

Trying to minimize log output a bit.

Don't log all reachabilites for every request

---

src/monitoring_service/database.py
src/monitoring_service/handlers.py
src/monitoring_service/schema.sql
src/monitoring_service/service.py
src/pathfinding_service/database.py
src/pathfinding_service/schema.sql
src/pathfinding_service/service.py
src/raiden_libs/blockchain.py
src/raiden_libs/database.py
src/raiden_libs/states.py
tests/libs/fixtures/web3.py
tests/monitoring/request_collector/test_server.py

Also improve some variable names.
⚠️ This changes the DB format.

Fix typo in commit[t]ed

---

src/pathfinding_service/database.py
tests/pathfinding/test_service.py

This still allows another process to connect and read the database.

Fordbid concurrent database usage

---

src/pathfinding_service/model/token_network.py
tests/pathfinding/test_token_network.py

This will be helpful in case
https://github.com/raiden-network/raiden/issues/5433#issuecomment-563304716
happens, again.

Add more logging to capacity handling

---

src/pathfinding_service/api.py

Add more debug information about IOUs

---

setup.cfg

Enable 'strict_equality' in mypy

---

src/pathfinding_service/api.py
src/pathfinding_service/database.py
src/pathfinding_service/model/token_network.py
src/pathfinding_service/service.py
src/raiden_libs/matrix.py
tests/libs/test_matrix.py
tests/monitoring/monitoring_service/test_database.py
tests/pathfinding/test_api.py
tests/pathfinding/test_fee_updates.py

Improves logging for the "Checking IOU" step to better debug #5684

Improving logging and linting

---

requirements.txt
src/raiden_libs/matrix.py
tests/libs/test_matrix.py

After https://github.com/raiden-network/raiden/pull/5728

Upgrade to latest raiden

---

requirements.txt

Update raiden, marshmallow and sentry

---

setup.cfg
src/monitoring_service/states.py
src/pathfinding_service/api.py
src/pathfinding_service/database.py
src/pathfinding_service/exceptions.py
src/pathfinding_service/model/channel.py
src/pathfinding_service/service.py
src/raiden_libs/contract_info.py
src/raiden_libs/matrix.py
src/request_collector/server.py
tests/monitoring/monitoring_service/factories.py
tests/pathfinding/test_api.py

This makes function signatures a bit more explicit.

Enable `no-implicit-optional`

---

src/pathfinding_service/service.py
src/request_collector/server.py

This should make debugging easier. It will only help in those cases
where we get a sentry error report, though. Which does not happen in all
desired cases, yet.

Add message/event to sentry error messages

---

.circleci/config.yml
requirements-dev.txt

- Unpin `pip`
- Add `-U` flag to `pip install`

Minor pip changes

---

requirements-dev.txt
requirements.txt

Update to latest mypy

---

deployment/docker-compose.yml

We currently don't use fludentd any more

Default to journald in deployment

---

src/monitoring_service/cli.py
src/pathfinding_service/cli.py
src/raiden_libs/register_service.py

Logs some more info during registration

Add contract infos to registration script

---

requirements.txt
src/monitoring_service/cli.py
src/monitoring_service/handlers.py
src/monitoring_service/service.py
src/pathfinding_service/api.py
src/pathfinding_service/claim_fees.py
src/pathfinding_service/cli.py
src/pathfinding_service/middleware.py
src/pathfinding_service/service.py
src/raiden_libs/blockchain.py
src/raiden_libs/cli.py
src/raiden_libs/register_service.py
tests/libs/test_matrix.py
tests/monitoring/monitoring_service/test_cli.py
tests/monitoring/monitoring_service/test_crash.py
tests/monitoring/monitoring_service/test_end_to_end.py
tests/monitoring/monitoring_service/test_handlers.py
tests/pathfinding/fixtures/iou.py
tests/pathfinding/test_blockchain_integration.py
tests/pathfinding/test_cli.py
tests/pathfinding/test_middleware.py
tests/pathfinding/test_service.py

Update raiden, fix typing problems

---

deployment/docker-compose.yml
setup.py
src/raiden_libs/cli.py
src/raiden_libs/contract_info.py
src/raiden_libs/register_service.py
src/raiden_libs/service_registry.py
tests/libs/test_register_service.py

Add `withdraw` command and rename `register_service `

---

src/pathfinding_service/api.py
src/pathfinding_service/service.py
tests/pathfinding/fixtures/network_service.py
tests/pathfinding/test_api.py

Add service token address to /info endpoint

---

src/raiden_libs/service_registry.py

Use caller address as default for SR withdraw

---

docs/index.rst
src/raiden_libs/cli.py
tests/monitoring/fixtures/server.py
tests/pathfinding/test_cli.py

Mostly for consistency (and my OCD 🙈 )

Add contract suffix to token netwrok registry CLI option

---

deployment/docker-compose.yml

Not sure, but `${MS_ACCEPT_DISCLAIMER}` should evaluate to something falsy if the envvar is not set, right?

Use disclamer vars in compose file

---

src/pathfinding_service/api.py
src/pathfinding_service/constants.py
tests/pathfinding/fixtures/api.py
tests/pathfinding/test_api.py

Remove the registry address, as it's available in the info ass well now.

Simplify default PFS info message

---

.bumpversion.cfg
CHANGELOG.md
Dockerfile
docs/conf.py
setup.py

Make another release to be able to integrate this into the RSB

Release 0.7.1

---

src/raiden_libs/service_registry.py

Reset token allowance if necessary

---

src/pathfinding_service/api.py
src/pathfinding_service/model/token_network.py

Added context for the existing values and the estimated block for the
time of the error.

Extended error messages

---

src/raiden_libs/blockchain.py

Add DeprecationSwitchEvent

---

src/raiden_libs/blockchain.py
tests/libs/test_blockchain.py
tests/monitoring/monitoring_service/test_end_to_end.py

This avoids recreating this dictionary every time the blockchain is
queried.
Fixes #794

Store event topics to abi dict in constant

---

tools/README.md
tools/pfs-view-stats.html

Includes some simple charts. Should be useful during the raiddit demo.
See https://github.com/raiden-network/raiddit/issues/43.

Add HTML page to view PFS stats

---

Dockerfile
pyproject.toml
src/pathfinding_service/api.py
src/pathfinding_service/database.py
src/pathfinding_service/service.py

WIP
- untested
- endpoint mapping not there yet
Fixes: https://github.com/raiden-network/raiddit/issues/63#issuecomment-665008823

Reload claims

---

src/pathfinding_service/api.py

Adding new values to `/_debug/stats` **not tested** for Raiddit

Adding total_minted and total_burned to stats endpoint

---

src/pathfinding_service/api.py
src/pathfinding_service/service.py

This reduces the load on the connection pool with the ETH node, so we should get rid of messages (and long response times) below:
```
pfs_1                | 172.20.0.60 - - [2020-07-30 12:23:55] "GET /api/v1/_debug/stats HTTP/1.1" 200 445 0.460177
pfs_1                | Connection pool is full, discarding connection: parity.goerli.ethnodes.brainbot.com
```

Only query total_burned/total_minted on new block

---

tests/conftest.py
tools/pfs-view-stats.html

Improve pfs viewer

---

CHANGELOG.md
src/monitoring_service/api.py
src/monitoring_service/constants.py
src/pathfinding_service/api.py
src/pathfinding_service/constants.py
tests/monitoring/monitoring_service/test_api.py
tests/pathfinding/test_api.py

Replacement for https://github.com/raiden-network/raiden-services/pull/861 that is backwards compatible.

Backwards compatible info

---

src/raiden_libs/service_registry.py

Cherry pick from https://github.com/raiden-network/raiden-services/pull/856

Fix typo in maybe_prompt

---

.github/auto_assign.yml

Update auto_assign list

---

.bumpversion.cfg
CHANGELOG.md
Dockerfile
docs/conf.py
setup.py

This will solve the issue of missed capacity updates in the matrix clients

Make new release 

---

docs/index.rst
src/pathfinding_service/api.py
src/raiden_libs/matrix.py
tests/constants.py
tests/libs/test_matrix.py
tests/pathfinding/fixtures/network_service.py
tests/pathfinding/test_api.py
tests/pathfinding/test_capacity_updates.py
tests/pathfinding/test_fee_updates.py

Broadcast rooms do not exist anymore with the upcoming release. This removes the usage of it

remove joining broadcast rooms

---

.bumpversion.cfg
CHANGELOG.md
Dockerfile
docs/conf.py
setup.py
src/raiden_libs/service_registry.py

Needed for https://github.com/raiden-network/light-client/issues/2699

Fix a crash of the `service_registry` script on private chains

---

src/raiden_libs/service_registry.py

Follow-up for https://github.com/raiden-network/raiden-services/pull/1005 with a missing adaption.

SR: Fix txhash display on private chains

---

.github/workflows/pythonpackage.yml
CHANGELOG.md
setup.py
src/raiden_libs/cli.py

~~Blocked by https://github.com/raiden-network/raiden/issues/6703~~

Support Python 3.9

---

src/pathfinding_service/api.py
tests/pathfinding/test_api.py

assure displayname is present on metadata response

---

.bumpversion.cfg
CHANGELOG.md
Dockerfile
docs/conf.py
setup.py

Release 0.17

---

src/raiden_libs/service_registry.py

The service_registry CLI tool used to shell out to ping to check if a given service URL is reachable.
This is problematic on multiple levels:
- The `ping` binary may not be available (as has happened in the RSB containers)
- A server operator my block ICMP requests for whatever reason
This replaces the ping check with a direct request to the PFS API `info` endpoint.
Fixes #1065

Service Registry: Query PFS info endpoint instead of shelling out to ping

---

.bumpversion.cfg
CHANGELOG.md
Dockerfile
docs/conf.py
setup.py

Release 0.17.1

---

src/raiden_libs/service_registry.py
tests/libs/test_service_registry.py

register: Display approximate cost before registration

---

.bumpversion.cfg
CHANGELOG.md
Dockerfile
docs/conf.py
setup.py

Release 1.0

---

.github/workflows/pythonpackage.yml

This would have helped when working on the arbitrum branches.

Trigger CI for PRs on all branches

---

.github/workflows/pythonpackage.yml
README.md
deployment/builder/Dockerfile
docs/index.rst
setup.py
src/monitoring_service/constants.py
src/monitoring_service/database.py
src/monitoring_service/handlers.py
src/monitoring_service/service.py
tests/monitoring/monitoring_service/test_end_to_end.py

Closes https://github.com/raiden-network/raiden-services/issues/1153.
I also cherry picked d9f200dac55ed00ff19348783ebedf2a20ebe50d from master, along with 9150691.

Reduce the amount of retries for too early events

---

src/monitoring_service/handlers.py

See commit message for details.

fix usage of eth-tester import in production

---

src/monitoring_service/database.py
src/monitoring_service/events.py
src/monitoring_service/metrics.py
src/monitoring_service/service.py
src/monitoring_service/states.py
src/pathfinding_service/api.py
src/pathfinding_service/claim_fees.py
src/pathfinding_service/cli.py
src/pathfinding_service/database.py
src/pathfinding_service/model/channel.py
src/pathfinding_service/model/iou.py
src/pathfinding_service/model/token_network.py
src/pathfinding_service/service.py
src/raiden_libs/blockchain.py
src/raiden_libs/cli.py
src/raiden_libs/contract_info.py
src/raiden_libs/database.py
src/raiden_libs/events.py
src/raiden_libs/matrix.py
src/raiden_libs/states.py
src/request_collector/server.py
tests/conftest.py
tests/monitoring/monitoring_service/factories.py
tests/pathfinding/test_api.py

In preparation of https://github.com/raiden-network/raiden/issues/7506, I try to reduce the amount of dependencies on the raiden package.
Except for the removal of the profiling options, this PR should be non-controversial.

Reduce raiden deps

---

src/monitoring_service/handlers.py

Closes #1166
I'll test this now already in practice for our Arbitrum Rinkeby RSB setup.

retry too early claim reward transactions

---

src/monitoring_service/handlers.py
src/monitoring_service/service.py
src/pathfinding_service/api.py
src/pathfinding_service/claim_fees.py
src/raiden_libs/utils.py
tests/monitoring/monitoring_service/test_handlers.py
tests/monitoring/monitoring_service/test_service.py
tests/pathfinding/test_api.py

fix wrong UTC timestamp usage
